% file: shallow_schreier_tree_node_17_2_draw_tree.mp
% created by Orbiter metapost interface
% creation date: Mon Nov 25 10:46:04 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
draw (500u ,925u )--(500u ,775u );
path pp;
pp = (502u ,925u ) .. (500u ,927u ) .. (498u ,925u ) .. (500u ,923u ) .. (502u ,925u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,925u ) .. (500u ,927u ) .. (498u ,925u ) .. (500u ,923u ) .. (502u ,925u ) .. cycle;
draw pp;
path pp;
pp = (502u ,775u ) .. (500u ,777u ) .. (498u ,775u ) .. (500u ,773u ) .. (502u ,775u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,775u ) .. (500u ,777u ) .. (498u ,775u ) .. (500u ,773u ) .. (502u ,775u ) .. cycle;
draw pp;
draw (-10u ,815u )--(-10u ,765u )--(40u ,765u );
draw (960u ,765u )--(1010u ,765u )--(1010u ,815u );
draw (960u ,935u )--(1010u ,935u )--(1010u ,885u );
draw (-10u ,885u )--(-10u ,935u )--(40u ,935u );
endfig;

end

