% file: shallow_schreier_tree_node_19_0_draw_tree.mp
% created by Orbiter metapost interface
% creation date: Mon Nov 25 10:46:05 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
path pp;
pp = (502u ,850u ) .. (500u ,852u ) .. (498u ,850u ) .. (500u ,848u ) .. (502u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,850u ) .. (500u ,852u ) .. (498u ,850u ) .. (500u ,848u ) .. (502u ,850u ) .. cycle;
draw pp;
draw (-10u ,890u )--(-10u ,840u )--(40u ,840u );
draw (960u ,840u )--(1010u ,840u )--(1010u ,890u );
draw (960u ,860u )--(1010u ,860u )--(1010u ,810u );
draw (-10u ,810u )--(-10u ,860u )--(40u ,860u );
endfig;

end

