% file: shallow_schreier_tree_node_15_0_draw_tree.mp
% created by Orbiter metapost interface
% creation date: Mon Nov 25 10:46:03 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
draw (500u ,950u )--(100u ,850u );
draw (500u ,950u )--(300u ,850u );
draw (500u ,950u )--(700u ,850u );
draw (700u ,850u )--(550u ,750u );
draw (700u ,850u )--(850u ,750u );
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
draw pp;
path pp;
pp = (102u ,850u ) .. (100u ,852u ) .. (98u ,850u ) .. (100u ,848u ) .. (102u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (102u ,850u ) .. (100u ,852u ) .. (98u ,850u ) .. (100u ,848u ) .. (102u ,850u ) .. cycle;
draw pp;
path pp;
pp = (302u ,850u ) .. (300u ,852u ) .. (298u ,850u ) .. (300u ,848u ) .. (302u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (302u ,850u ) .. (300u ,852u ) .. (298u ,850u ) .. (300u ,848u ) .. (302u ,850u ) .. cycle;
draw pp;
path pp;
pp = (702u ,850u ) .. (700u ,852u ) .. (698u ,850u ) .. (700u ,848u ) .. (702u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (702u ,850u ) .. (700u ,852u ) .. (698u ,850u ) .. (700u ,848u ) .. (702u ,850u ) .. cycle;
draw pp;
path pp;
pp = (552u ,750u ) .. (550u ,752u ) .. (548u ,750u ) .. (550u ,748u ) .. (552u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (552u ,750u ) .. (550u ,752u ) .. (548u ,750u ) .. (550u ,748u ) .. (552u ,750u ) .. cycle;
draw pp;
path pp;
pp = (852u ,750u ) .. (850u ,752u ) .. (848u ,750u ) .. (850u ,748u ) .. (852u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (852u ,750u ) .. (850u ,752u ) .. (848u ,750u ) .. (850u ,748u ) .. (852u ,750u ) .. cycle;
draw pp;
draw (-10u ,790u )--(-10u ,740u )--(40u ,740u );
draw (960u ,740u )--(1010u ,740u )--(1010u ,790u );
draw (960u ,960u )--(1010u ,960u )--(1010u ,910u );
draw (-10u ,910u )--(-10u ,960u )--(40u ,960u );
endfig;

end

