% file: shallow_schreier_tree_node_20_1_draw_tree.mp
% created by Orbiter metapost interface
% creation date: Mon Nov 25 10:46:06 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
draw (500u ,950u )--(300u ,850u );
draw (500u ,950u )--(700u ,850u );
draw (500u ,950u )--(900u ,850u );
draw (300u ,850u )--(150u ,750u );
draw (300u ,850u )--(450u ,750u );
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
draw pp;
path pp;
pp = (302u ,850u ) .. (300u ,852u ) .. (298u ,850u ) .. (300u ,848u ) .. (302u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (302u ,850u ) .. (300u ,852u ) .. (298u ,850u ) .. (300u ,848u ) .. (302u ,850u ) .. cycle;
draw pp;
path pp;
pp = (702u ,850u ) .. (700u ,852u ) .. (698u ,850u ) .. (700u ,848u ) .. (702u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (702u ,850u ) .. (700u ,852u ) .. (698u ,850u ) .. (700u ,848u ) .. (702u ,850u ) .. cycle;
draw pp;
path pp;
pp = (902u ,850u ) .. (900u ,852u ) .. (898u ,850u ) .. (900u ,848u ) .. (902u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (902u ,850u ) .. (900u ,852u ) .. (898u ,850u ) .. (900u ,848u ) .. (902u ,850u ) .. cycle;
draw pp;
path pp;
pp = (152u ,750u ) .. (150u ,752u ) .. (148u ,750u ) .. (150u ,748u ) .. (152u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (152u ,750u ) .. (150u ,752u ) .. (148u ,750u ) .. (150u ,748u ) .. (152u ,750u ) .. cycle;
draw pp;
path pp;
pp = (452u ,750u ) .. (450u ,752u ) .. (448u ,750u ) .. (450u ,748u ) .. (452u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (452u ,750u ) .. (450u ,752u ) .. (448u ,750u ) .. (450u ,748u ) .. (452u ,750u ) .. cycle;
draw pp;
draw (-10u ,790u )--(-10u ,740u )--(40u ,740u );
draw (960u ,740u )--(1010u ,740u )--(1010u ,790u );
draw (960u ,960u )--(1010u ,960u )--(1010u ,910u );
draw (-10u ,910u )--(-10u ,960u )--(40u ,960u );
endfig;

end

