% file: shallow_schreier_tree_node_12_0_draw_tree.mp
% created by Orbiter metapost interface
% creation date: Mon Nov 25 10:46:02 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
draw (500u ,950u )--(100u ,850u );
draw (500u ,950u )--(400u ,850u );
draw (500u ,950u )--(800u ,850u );
draw (400u ,850u )--(400u ,750u );
draw (800u ,850u )--(800u ,750u );
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (502u ,950u ) .. (500u ,952u ) .. (498u ,950u ) .. (500u ,948u ) .. (502u ,950u ) .. cycle;
draw pp;
path pp;
pp = (102u ,850u ) .. (100u ,852u ) .. (98u ,850u ) .. (100u ,848u ) .. (102u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (102u ,850u ) .. (100u ,852u ) .. (98u ,850u ) .. (100u ,848u ) .. (102u ,850u ) .. cycle;
draw pp;
path pp;
pp = (402u ,850u ) .. (400u ,852u ) .. (398u ,850u ) .. (400u ,848u ) .. (402u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (402u ,850u ) .. (400u ,852u ) .. (398u ,850u ) .. (400u ,848u ) .. (402u ,850u ) .. cycle;
draw pp;
path pp;
pp = (802u ,850u ) .. (800u ,852u ) .. (798u ,850u ) .. (800u ,848u ) .. (802u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (802u ,850u ) .. (800u ,852u ) .. (798u ,850u ) .. (800u ,848u ) .. (802u ,850u ) .. cycle;
draw pp;
path pp;
pp = (402u ,750u ) .. (400u ,752u ) .. (398u ,750u ) .. (400u ,748u ) .. (402u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (402u ,750u ) .. (400u ,752u ) .. (398u ,750u ) .. (400u ,748u ) .. (402u ,750u ) .. cycle;
draw pp;
path pp;
pp = (802u ,750u ) .. (800u ,752u ) .. (798u ,750u ) .. (800u ,748u ) .. (802u ,750u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (802u ,750u ) .. (800u ,752u ) .. (798u ,750u ) .. (800u ,748u ) .. (802u ,750u ) .. cycle;
draw pp;
draw (-10u ,790u )--(-10u ,740u )--(40u ,740u );
draw (960u ,740u )--(1010u ,740u )--(1010u ,790u );
draw (960u ,960u )--(1010u ,960u )--(1010u ,910u );
draw (-10u ,910u )--(-10u ,960u )--(40u ,960u );
endfig;

end

