var dir_c0c648a179fe4f40b8c6c32cce3eaa8c =
[
    [ "DATA", "dir_3bc26b5431e514b448e0c11f325e5626.html", "dir_3bc26b5431e514b448e0c11f325e5626" ],
    [ "andre_construction.C", "d9/d40/andre__construction_8_c.html", null ],
    [ "andre_construction_line_element.C", "d6/d9b/andre__construction__line__element_8_c.html", null ],
    [ "andre_construction_point_element.C", "d7/db3/andre__construction__point__element_8_c.html", null ],
    [ "buekenhout_metz.C", "de/d32/buekenhout__metz_8_c.html", "de/d32/buekenhout__metz_8_c" ],
    [ "data.C", "d7/d94/data_8_c.html", "d7/d94/data_8_c" ],
    [ "decomposition.C", "d6/d7a/foundations_2geometry_2decomposition_8_c.html", null ],
    [ "desarguesian_spread.C", "de/d46/lib_2foundations_2geometry_2desarguesian__spread_8_c.html", null ],
    [ "eckardt_point.C", "d0/d8f/eckardt__point_8_c.html", null ],
    [ "flag.C", "db/db7/flag_8_c.html", null ],
    [ "geo_parameter.C", "d0/d96/geo__parameter_8_c.html", "d0/d96/geo__parameter_8_c" ],
    [ "geometric_object.C", "d4/d58/geometric__object_8_c.html", "d4/d58/geometric__object_8_c" ],
    [ "geometric_operations.C", "da/d76/geometric__operations_8_c.html", "da/d76/geometric__operations_8_c" ],
    [ "geometry.h", "d4/d67/geometry_8h.html", "d4/d67/geometry_8h" ],
    [ "grassmann.C", "d4/d20/lib_2foundations_2geometry_2grassmann_8_c.html", null ],
    [ "grassmann_embedded.C", "d5/dd2/grassmann__embedded_8_c.html", null ],
    [ "hermitian.C", "d4/df7/hermitian_8_c.html", null ],
    [ "hjelmslev.C", "d2/d83/hjelmslev_8_c.html", null ],
    [ "inc_gen_global.C", "d3/d00/inc__gen__global_8_c.html", "d3/d00/inc__gen__global_8_c" ],
    [ "incidence_structure.C", "dd/d17/foundations_2geometry_2incidence__structure_8_c.html", "dd/d17/foundations_2geometry_2incidence__structure_8_c" ],
    [ "klein_correspondence.C", "d7/d73/klein__correspondence_8_c.html", null ],
    [ "knarr.C", "d9/d77/knarr_8_c.html", null ],
    [ "object_in_projective_space.C", "dc/d52/object__in__projective__space_8_c.html", null ],
    [ "orthogonal.C", "d3/d65/lib_2foundations_2geometry_2orthogonal_8_c.html", null ],
    [ "orthogonal_points.C", "db/da0/lib_2foundations_2geometry_2orthogonal__points_8_c.html", "db/da0/lib_2foundations_2geometry_2orthogonal__points_8_c" ],
    [ "packing.C", "de/d59/lib_2foundations_2geometry_2packing_8_c.html", "de/d59/lib_2foundations_2geometry_2packing_8_c" ],
    [ "point_line.C", "d0/d75/point__line_8_c.html", "d0/d75/point__line_8_c" ],
    [ "projective.C", "df/de4/projective_8_c.html", "df/de4/projective_8_c" ],
    [ "projective_space.C", "d1/dbe/foundations_2geometry_2projective__space_8_c.html", "d1/dbe/foundations_2geometry_2projective__space_8_c" ],
    [ "surface.C", "d7/dd9/surface_8_c.html", null ],
    [ "surface_object.C", "da/d7a/surface__object_8_c.html", null ],
    [ "tdo_data.C", "dd/da0/tdo__data_8_c.html", null ],
    [ "tdo_scheme.C", "d8/db0/tdo__scheme_8_c.html", null ],
    [ "unusual.C", "d6/d5c/unusual_8_c.html", null ],
    [ "w3q.C", "dc/dca/w3q_8_c.html", null ]
];