var dir_8c80f49af6b49ba0e84a9c44b4de0559 =
[
    [ "arc_generator.C", "d7/d4e/arc__generator_8_c.html", "d7/d4e/arc__generator_8_c" ],
    [ "arc_lifting.C", "d6/d89/arc__lifting_8_c.html", null ],
    [ "BLT_set_create.C", "db/da3/_b_l_t__set__create_8_c.html", null ],
    [ "BLT_set_create_description.C", "de/d08/_b_l_t__set__create__description_8_c.html", null ],
    [ "choose_points_or_lines.C", "d5/d31/choose__points__or__lines_8_c.html", null ],
    [ "classify_double_sixes.C", "db/d27/classify__double__sixes_8_c.html", null ],
    [ "classify_trihedral_pairs.C", "dc/d0b/classify__trihedral__pairs_8_c.html", "dc/d0b/classify__trihedral__pairs_8_c" ],
    [ "decomposition.C", "db/d10/top__level_2geometry_2decomposition_8_c.html", "db/d10/top__level_2geometry_2decomposition_8_c" ],
    [ "incidence_structure.C", "d3/d0e/top__level_2geometry_2incidence__structure_8_c.html", "d3/d0e/top__level_2geometry_2incidence__structure_8_c" ],
    [ "k_arc_generator.C", "d3/df4/k__arc__generator_8_c.html", null ],
    [ "object_in_projective_space_with_action.C", "da/d25/object__in__projective__space__with__action_8_c.html", null ],
    [ "polar.C", "d4/dc2/lib_2top__level_2geometry_2polar_8_c.html", "d4/dc2/lib_2top__level_2geometry_2polar_8_c" ],
    [ "projective_space.C", "d6/de8/top__level_2geometry_2projective__space_8_c.html", "d6/de8/top__level_2geometry_2projective__space_8_c" ],
    [ "recoordinatize.C", "d3/de8/recoordinatize_8_c.html", null ],
    [ "search_blocking_set.C", "d4/d64/search__blocking__set_8_c.html", "d4/d64/search__blocking__set_8_c" ],
    [ "singer_cycle.C", "d8/dc7/singer__cycle_8_c.html", null ],
    [ "six_arcs_not_on_a_conic.C", "d2/d51/six__arcs__not__on__a__conic_8_c.html", null ],
    [ "spread.C", "d7/d2e/spread_8_c.html", "d7/d2e/spread_8_c" ],
    [ "spread2.C", "db/dd4/spread2_8_c.html", "db/dd4/spread2_8_c" ],
    [ "spread_create.C", "d7/d76/lib_2top__level_2geometry_2spread__create_8_c.html", null ],
    [ "spread_create_description.C", "d8/d66/spread__create__description_8_c.html", null ],
    [ "spread_lifting.C", "de/d8d/spread__lifting_8_c.html", null ],
    [ "surface_classify_wedge.C", "d6/db8/surface__classify__wedge_8_c.html", null ],
    [ "surface_create.C", "dc/d03/surface__create_8_c.html", null ],
    [ "surface_create_description.C", "db/dcb/surface__create__description_8_c.html", null ],
    [ "surface_object_with_action.C", "dc/ddf/surface__object__with__action_8_c.html", null ],
    [ "surface_with_action.C", "df/d30/surface__with__action_8_c.html", null ],
    [ "tl_geometry.h", "df/d74/tl__geometry_8h.html", "df/d74/tl__geometry_8h" ],
    [ "translation_plane_via_andre_model.C", "d4/d8c/translation__plane__via__andre__model_8_c.html", "d4/d8c/translation__plane__via__andre__model_8_c" ]
];