var dir_5c582f139252af33e3d4366a6bdd9052 =
[
    [ "analyze.C", "da/d90/analyze_8_c.html", "da/d90/analyze_8_c" ],
    [ "analyze_projective_code.C", "dd/da1/analyze__projective__code_8_c.html", "dd/da1/analyze__projective__code_8_c" ],
    [ "analyze_q_designs.C", "d8/d03/analyze__q__designs_8_c.html", "d8/d03/analyze__q__designs_8_c" ],
    [ "baer_subplane.C", "d7/d86/baer__subplane_8_c.html", "d7/d86/baer__subplane_8_c" ],
    [ "cheat_sheet_PG.C", "d6/dd8/cheat__sheet___p_g_8_c.html", "d6/dd8/cheat__sheet___p_g_8_c" ],
    [ "determine_conic.C", "de/d27/determine__conic_8_c.html", "de/d27/determine__conic_8_c" ],
    [ "determine_quadric.C", "d7/d9d/determine__quadric_8_c.html", "d7/d9d/determine__quadric_8_c" ],
    [ "example_fano_plane.C", "d9/d5f/example__fano__plane_8_c.html", "d9/d5f/example__fano__plane_8_c" ],
    [ "export_data.C", "d5/dcc/export__data_8_c.html", "d5/dcc/export__data_8_c" ],
    [ "factor_space.C", "d9/db0/factor__space_8_c.html", "d9/db0/factor__space_8_c" ],
    [ "hill.C", "da/d28/hill_8_c.html", "da/d28/hill_8_c" ],
    [ "make_BLT_set.C", "d7/dbe/make___b_l_t__set_8_c.html", "d7/dbe/make___b_l_t__set_8_c" ],
    [ "make_grassmannian.C", "d9/d3a/make__grassmannian_8_c.html", "d9/d3a/make__grassmannian_8_c" ],
    [ "make_group.C", "dd/d51/make__group_8_c.html", "dd/d51/make__group_8_c" ],
    [ "make_something.C", "d4/d6e/make__something_8_c.html", "d4/d6e/make__something_8_c" ],
    [ "orthogonal_points.C", "d9/d2b/apps_2projective__space_2orthogonal__points_8_c.html", "d9/d2b/apps_2projective__space_2orthogonal__points_8_c" ],
    [ "ovoid.C", "d9/dbf/projective__space_2ovoid_8_c.html", "d9/dbf/projective__space_2ovoid_8_c" ],
    [ "plane_search.C", "dd/d07/plane__search_8_c.html", "dd/d07/plane__search_8_c" ],
    [ "points.C", "d7/d83/points_8_c.html", "d7/d83/points_8_c" ],
    [ "polar.C", "d5/d0d/apps_2projective__space_2polar_8_c.html", "d5/d0d/apps_2projective__space_2polar_8_c" ],
    [ "process.C", "d0/d2f/process_8_c.html", "d0/d2f/process_8_c" ],
    [ "process_PG.C", "d7/d29/process___p_g_8_c.html", "d7/d29/process___p_g_8_c" ],
    [ "projective_space_main.C", "d0/de6/projective__space__main_8_c.html", "d0/de6/projective__space__main_8_c" ],
    [ "simeon.C", "d5/d13/simeon_8_c.html", "d5/d13/simeon_8_c" ],
    [ "test_PG.C", "d0/d8c/test___p_g_8_c.html", "d0/d8c/test___p_g_8_c" ]
];