/*
 * group_theoretic_activity_for_surfaces.cpp
 *
 *  Created on: Oct 19, 2020
 *      Author: betten
 */




#include "orbiter.h"

using namespace std;

namespace orbiter {
namespace top_level {




void group_theoretic_activity::do_create_surface(
		surface_create_description *Surface_Descr,
		poset_classification_control *Control_six_arcs,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface" << endl;
		cout << "group_theoretic_activity::do_create_surface verbose_level=" << verbose_level << endl;
	}

	int q;
	int i;
	finite_field *F;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	number_theory_domain NT;
	sorting Sorting;
	file_io Fio;

	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface before Surface_Descr->get_q" << endl;
	}
	q = Surface_Descr->get_q();
	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface q = " << q << endl;
	}


	F = LG->F;
	if (F->q != q) {
		cout << "F->q != q" << endl;
		exit(1);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface before Surf->init" << endl;
		}
	Surf = NEW_OBJECT(surface_domain);
	Surf->init(F, verbose_level - 1);
	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface after Surf->init" << endl;
		}

	Surf_A = NEW_OBJECT(surface_with_action);

	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface before Surf_A->init_with_linear_group" << endl;
		}
	Surf_A->init_with_linear_group(Surf, LG, TRUE /* f_recoordinatize */, 0 /*verbose_level*/);
	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface after Surf_A->init_with_linear_group" << endl;
		}


	surface_create *SC;
	SC = NEW_OBJECT(surface_create);

	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface before SC->init" << endl;
	}
	SC->init(Surface_Descr, Surf_A, verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface after SC->init" << endl;
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface "
				"before SC->apply_transformations" << endl;
	}
	SC->apply_transformations(Surface_Descr->transform_coeffs,
				Surface_Descr->f_inverse_transform,
				verbose_level - 2);

	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface "
				"after SC->apply_transformations" << endl;
	}




	int coeffs_out[20];
	action *A;
	//int *Elt1;
	int *Elt2;

	A = SC->Surf_A->A;

	Elt2 = NEW_int(A->elt_size_in_int);

	//SC->F->init_symbol_for_print("\\omega");

	if (SC->F->e == 1) {
		SC->F->f_print_as_exponentials = FALSE;
	}

	SC->F->PG_element_normalize(SC->SO->eqn, 1, 20);

	cout << "group_theoretic_activity::do_create_surface "
			"We have created the following surface:" << endl;
	cout << "$$" << endl;
	SC->Surf->print_equation_tex(cout, SC->SO->eqn);
	cout << endl;
	cout << "$$" << endl;

	cout << "$$" << endl;
	int_vec_print(cout, SC->SO->eqn, 20);
	cout << endl;
	cout << "$$" << endl;


	if (SC->f_has_group) {

		// test the generators:

		for (i = 0; i < SC->Sg->gens->len; i++) {
			cout << "group_theoretic_activity::do_create_surface "
					"Testing generator " << i << " / "
					<< SC->Sg->gens->len << endl;
			A->element_invert(SC->Sg->gens->ith(i),
					Elt2, 0 /*verbose_level*/);



			matrix_group *M;

			M = A->G.matrix_grp;
			M->substitute_surface_equation(Elt2,
					SC->SO->eqn, coeffs_out, SC->Surf,
					verbose_level - 1);


			if (int_vec_compare(SC->SO->eqn, coeffs_out, 20)) {
				cout << "group_theoretic_activity::do_create_surface error, "
						"the transformation does not preserve "
						"the equation of the surface" << endl;
				exit(1);
			}
			cout << "group_theoretic_activity::do_create_surface "
					"Generator " << i << " / " << SC->Sg->gens->len
					<< " is good" << endl;
		}
	}
	else {
		cout << "group_theoretic_activity::do_create_surface "
				"We do not have information about "
				"the automorphism group" << endl;
	}


	cout << "group_theoretic_activity::do_create_surface We have created "
			"the surface " << SC->label_txt << ":" << endl;
	cout << "$$" << endl;
	SC->Surf->print_equation_tex(cout, SC->SO->eqn);
	cout << endl;
	cout << "$$" << endl;

	if (SC->f_has_group) {
		cout << "group_theoretic_activity::do_create_surface "
				"The stabilizer is generated by:" << endl;
		SC->Sg->print_generators_tex(cout);

		if (SC->f_has_nice_gens) {
			cout << "group_theoretic_activity::do_create_surface "
					"The stabilizer is generated by the following nice generators:" << endl;
			SC->nice_gens->print_tex(cout);

		}
	}

#if 0
	if (SC->f_has_lines) {
		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"The lines are:" << endl;
			SC->Surf->Gr->print_set_tex(cout, SC->SO->Lines, SC->SO->nb_lines);
		}


		surface_object *SO;

		SO = NEW_OBJECT(surface_object);
		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface before SO->init_with_27_lines" << endl;
			}
		SO->init_with_27_lines(SC->Surf, SC->Lines, SC->coeffs,
				FALSE /*f_find_double_six_and_rearrange_lines */, verbose_level);
		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface after SO->init_with_27_lines" << endl;
			}

		string fname_points;

		fname_points.assign("surface_");
		fname_points.append(SC->label_txt);
		fname_points.append("_points.txt");
		Fio.write_set_to_file(fname_points, SO->Pts, SO->nb_pts, 0 /*verbose_level*/);
		cout << "group_theoretic_activity::do_create_surface "
				"Written file " << fname_points << " of size "
				<< Fio.file_size(fname_points) << endl;
	}
	else {
		cout << "group_theoretic_activity::do_create_surface "
				"The surface " << SC->label_txt
				<< " does not come with lines" << endl;
	}
#else
	string fname_points;

	fname_points.assign("surface_");
	fname_points.append(SC->label_txt);
	fname_points.append("_points.txt");
	Fio.write_set_to_file(fname_points, SC->SO->Pts, SC->SO->nb_pts, 0 /*verbose_level*/);
	cout << "group_theoretic_activity::do_create_surface "
			"Written file " << fname_points << " of size "
			<< Fio.file_size(fname_points) << endl;

#endif

	{
		string fname_report;

		if (SC->Descr->f_label_txt) {
			fname_report.assign(SC->Descr->label_txt);
			fname_report.append(".tex");

		}
		else {
			fname_report.assign("surface_");
			fname_report.append(SC->Descr->label_txt);
			fname_report.append("_report.tex");
		}

		{
			ofstream ost(fname_report);


			char title[1000];
			char author[1000];

			if (SC->Descr->f_label_tex) {
				snprintf(title, 1000, "%s over GF(%d)", SC->Descr->label_tex.c_str(), F->q);
			}
			else {
				snprintf(title, 1000, "Cubic Surface over GF(%d)", F->q);
			}
			strcpy(author, "");

			latex_interface L;

			//latex_head_easy(fp);
			L.head(ost,
				FALSE /* f_book */,
				TRUE /* f_title */,
				title, author,
				FALSE /*f_toc */,
				FALSE /* f_landscape */,
				FALSE /* f_12pt */,
				TRUE /*f_enlarged_page */,
				TRUE /* f_pagenumbers*/,
				NULL /* extra_praeamble */);




			//ost << "\\subsection*{The surface $" << SC->label_tex << "$}" << endl;


			if (SC->SO->SOP == NULL) {
				cout << "group_theoretic_activity::do_create_surface SC->SO->SOP == NULL" << endl;
				exit(1);
			}


			string summary_file_name;
			string col_postfix;

			if (SC->Descr->f_label_txt) {
				summary_file_name.assign(SC->Descr->label_txt);
			}
			else {
				summary_file_name.assign(SC->label_txt);
			}
			summary_file_name.append("_summary.csv");

			char str[1000];

			sprintf(str, "-Q%d", F->q);
			col_postfix.assign(str);

			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"before SC->SO->SOP->create_summary_file" << endl;
			}
			if (SC->Descr->f_label_for_summary) {
				SC->SO->SOP->create_summary_file(summary_file_name,
						SC->Descr->label_for_summary, col_postfix, verbose_level);
			}
			else {
				SC->SO->SOP->create_summary_file(summary_file_name,
						SC->label_txt, col_postfix, verbose_level);
			}
			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"after SC->SO->SOP->create_summary_file" << endl;
			}


#if 0
			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"before SC->SO->SOP->print_everything" << endl;
			}
			SC->SO->SOP->print_everything(ost, verbose_level);
			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"after SC->SO->SOP->print_everything" << endl;
			}
#else
			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"before SC->SO->SOP->report_properties_simple" << endl;
			}
			SC->SO->SOP->report_properties_simple(ost, verbose_level);
			if (f_v) {
				cout << "group_theoretic_activity::do_create_surface "
						"after SC->SO->SOP->report_properties_simple" << endl;
			}
#endif


			L.foot(ost);
		}
		file_io Fio;

		cout << "Written file " << fname_report << " of size "
			<< Fio.file_size(fname_report) << endl;


	}






	if (SC->f_has_group) {

		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface creating "
					"surface_object_with_action object" << endl;
		}

		surface_object_with_action *SoA;

		SoA = NEW_OBJECT(surface_object_with_action);

		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface before SoA->init_with_group" << endl;
		}
		SoA->init_with_group(
			SC->Surf_A,
			SC->SO->Lines, SC->SO->nb_lines,
			SC->SO->eqn,
			SC->Sg,
			FALSE /*f_find_double_six_and_rearrange_lines*/,
			SC->f_has_nice_gens, SC->nice_gens,
			verbose_level - 1);
		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface after SoA->init_with_group" << endl;
		}

		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"The surface has been created." << endl;
		}



		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"Classifying non-conical six-arcs." << endl;
		}

		six_arcs_not_on_a_conic *Six_arcs;
		arc_generator_description *Six_arc_descr;

		int *transporter;

		Six_arcs = NEW_OBJECT(six_arcs_not_on_a_conic);

		Six_arc_descr = NEW_OBJECT(arc_generator_description);
		Six_arc_descr->F = F;
		Six_arc_descr->f_q = TRUE;
		Six_arc_descr->q = F->q;
		Six_arc_descr->f_n = TRUE;
		Six_arc_descr->n = 3;
		Six_arc_descr->f_target_size = TRUE;
		Six_arc_descr->target_size = 6;
		Six_arc_descr->Control = Control_six_arcs;



		// classify six arcs not on a conic:

		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"Setting up the group of the plane:" << endl;
		}

		action *A;

		A = NEW_OBJECT(action);


		int f_semilinear = TRUE;
		number_theory_domain NT;

		if (NT.is_prime(F->q)) {
			f_semilinear = FALSE;
		}

		{
			vector_ge *nice_gens;
			A->init_projective_group(3, F,
					f_semilinear, TRUE /*f_basis*/, TRUE /* f_init_sims */,
					nice_gens,
					0 /*verbose_level*/);
			FREE_OBJECT(nice_gens);
		}


		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"before Six_arcs->init:" << endl;
		}


		Six_arcs->init(
				Six_arc_descr,
				A,
				SC->Surf->P2,
				FALSE, 0, NULL,
				verbose_level);

		transporter = NEW_int(Six_arcs->Gen->A->elt_size_in_int);


		if (f_v) {
			cout << "group_theoretic_activity::do_create_surface "
					"before SoA->investigate_surface_and_write_report:" << endl;
		}

		if (The_Orbiter_session->f_draw_options) {
			SoA->investigate_surface_and_write_report(
					The_Orbiter_session->draw_options,
					A,
					SC,
					Six_arcs,
					Descr->f_surface_clebsch,
					Descr->f_surface_codes,
					Descr->f_surface_quartic,
					verbose_level);
		}
		else {
			cout << "use -draw_options to specify the drawing option for the report" << endl;
			exit(1);
		}

		FREE_OBJECT(SoA);
		FREE_OBJECT(Six_arcs);
		FREE_OBJECT(Six_arc_descr);
		FREE_int(transporter);


		}
	else {
		cout << "We don't have the group of the surface" << endl;
	}



	FREE_int(Elt2);

	FREE_OBJECT(SC);


	if (f_v) {
		cout << "group_theoretic_activity::do_create_surface done" << endl;
	}
}



void group_theoretic_activity::do_surface_classify(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_classify" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;

	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_classify "
				"before Algebra.classify_surfaces, control=" << endl;
		Control->print();
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_classify "
				"after Algebra.classify_surfaces" << endl;
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_classify "
				"before SCW->generate_source_code" << endl;
	}
	SCW->generate_source_code(verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_classify "
				"after SCW->generate_source_code" << endl;
	}


	if (Descr->f_report) {

		layered_graph_draw_options *O;


		if (!The_Orbiter_session->f_draw_options) {
			cout << "please use option -draw_options .. -end" << endl;
			exit(1);
		}
		O = The_Orbiter_session->draw_options;


		SCW->create_report(TRUE /*f_with_stabilizers */,
				O,
				verbose_level);
	}

	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "interface_algebra::do_surface_classify done" << endl;
	}
}

void group_theoretic_activity::do_surface_report(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_report" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_report "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_report "
				"after Algebra.classify_surfaces" << endl;
	}

	int f_with_stabilizers = TRUE;

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_report "
				"before SCW->create_report" << endl;
	}
	SCW->create_report(f_with_stabilizers, Control->draw_options, verbose_level - 1);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_report "
				"after SCW->create_report" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "interface_algebra::do_surface_report done" << endl;
	}
}

void group_theoretic_activity::do_surface_identify_HCV(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV "
				"before SCW->identify_HCV_and_print_table" << endl;
	}
	SCW->identify_HCV_and_print_table(verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV "
				"after SCW->identify_HCV_and_print_table" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_HCV done" << endl;
	}
}

void group_theoretic_activity::do_surface_identify_F13(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13 "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13 "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13 "
				"before SCW->identify_HCV_and_print_table" << endl;
	}
	SCW->identify_F13_and_print_table(verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13 "
				"after SCW->identify_HCV_and_print_table" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_F13 done" << endl;
	}
}

void group_theoretic_activity::do_surface_identify_Bes(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes "
				"before SCW->identify_Bes_and_print_table" << endl;
	}
	SCW->identify_Bes_and_print_table(verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes "
				"after SCW->identify_Bes_and_print_table" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_Bes done" << endl;
	}
}

void group_theoretic_activity::do_surface_identify_general_abcd(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd "
				"before SCW->identify_general_abcd_and_print_table" << endl;
	}
	SCW->identify_general_abcd_and_print_table(verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd "
				"after SCW->identify_general_abcd_and_print_table" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_identify_general_abcd done" << endl;
	}
}

void group_theoretic_activity::do_surface_isomorphism_testing(
		surface_create_description *surface_descr_isomorph1,
		surface_create_description *surface_descr_isomorph2,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing "
				"before SCW->test_isomorphism" << endl;
	}
	SCW->test_isomorphism(
			surface_descr_isomorph1,
			surface_descr_isomorph2,
			verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing "
				"after SCW->test_isomorphism" << endl;
	}


	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_isomorphism_testing done" << endl;
	}
}

void group_theoretic_activity::do_surface_recognize(
		surface_create_description *surface_descr,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize" << endl;
	}

	algebra_global_with_action Algebra;
	surface_domain *Surf;
	surface_with_action *Surf_A;
	surface_classify_wedge *SCW;
	poset_classification_control *Control;

	if (Descr->f_poset_classification_control) {
		Control = Descr->Control;
	}
	else {
		Control = NEW_OBJECT(poset_classification_control);
	}


	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize "
				"before Algebra.classify_surfaces" << endl;
	}
	Algebra.classify_surfaces(
			F, LG,
			Control,
			Surf, Surf_A,
			SCW,
			verbose_level - 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize "
				"after Algebra.classify_surfaces" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize "
				"before SCW->recognition" << endl;
	}
	SCW->recognition(
			surface_descr,
			verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize "
				"after SCW->recognition" << endl;
	}

	FREE_OBJECT(SCW);
	FREE_OBJECT(Surf_A);
	FREE_OBJECT(Surf);
	if (f_v) {
		cout << "group_theoretic_activity::do_surface_recognize done" << endl;
	}
}





void group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines(
		poset_classification_control *Control_six_arcs,
		int f_test_nb_Eckardt_points, int nb_E,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines" << endl;
	}

	surface_with_action *Surf_A;
	surface_domain *Surf;
	number_theory_domain NT;



	Surf = NEW_OBJECT(surface_domain);
	Surf_A = NEW_OBJECT(surface_with_action);


	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"before Surf->init" << endl;
	}
	Surf->init(F, 0 /*verbose_level*/);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"after Surf->init" << endl;
	}


#if 0
	if (f_v) {
		cout << "before Surf->init_large_polynomial_domains" << endl;
	}
	Surf->init_large_polynomial_domains(0 /*verbose_level*/);
	if (f_v) {
		cout << "after Surf->init_large_polynomial_domains" << endl;
	}
#endif


	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"before Surf_A->init_with_linear_group" << endl;
	}
	Surf_A->init_with_linear_group(Surf, LG, TRUE /* f_recoordinatize */, 0 /*verbose_level - 1*/);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"after Surf_A->init_with_linear_group" << endl;
	}


	surfaces_arc_lifting *SAL;

	SAL = NEW_OBJECT(surfaces_arc_lifting);

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"before SAL->init" << endl;
	}
	SAL->init(
		LG->F, LG /* LG4 */,
		Surf_A,
		Control_six_arcs,
		f_test_nb_Eckardt_points, nb_E,
		verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
				"after SAL->init" << endl;
	}

	if (Descr->f_report) {
		if (f_v) {
			cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
					"before SAL->report" << endl;
		}
		SAL->report(Control_six_arcs->draw_options, verbose_level);
		if (f_v) {
			cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines "
					"after SAL->report" << endl;
		}

	}
	FREE_OBJECT(SAL);


	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_two_lines done" << endl;
	}

}

void group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs(
		poset_classification_control *Control1,
		poset_classification_control *Control2,
		poset_classification_control *Control_six_arcs,
		int f_test_nb_Eckardt_points, int nb_E,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs" << endl;
	}

	surface_with_action *Surf_A;
	surface_domain *Surf;
	number_theory_domain NT;



	Surf = NEW_OBJECT(surface_domain);
	Surf_A = NEW_OBJECT(surface_with_action);


	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"before Surf->init" << endl;
	}
	Surf->init(F, verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"after Surf->init" << endl;
	}


#if 0
	if (f_v) {
		cout << "before Surf->init_large_polynomial_domains" << endl;
	}
	Surf->init_large_polynomial_domains(0 /*verbose_level*/);
	if (f_v) {
		cout << "after Surf->init_large_polynomial_domains" << endl;
	}
#endif


	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"before Surf_A->init_with_linear_group" << endl;
	}
	Surf_A->init_with_linear_group(Surf, LG, TRUE /* f_recoordinatize */, verbose_level - 1);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"after Surf_A->init_with_linear_group" << endl;
	}



	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"before Surf_A->Classify_trihedral_pairs->classify" << endl;
	}
	Surf_A->Classify_trihedral_pairs->classify(Control1, Control2, verbose_level);
	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"after Surf_A->Classify_trihedral_pairs->classify" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"before Surf_arc->classify_surfaces_through_arcs_and_trihedral_pairs" << endl;
	}

	surface_classify_using_arc *Surf_arc;

	Surf_arc = NEW_OBJECT(surface_classify_using_arc);


	Surf_arc->classify_surfaces_through_arcs_and_trihedral_pairs(
			Control_six_arcs,
			Surf_A,
			f_test_nb_Eckardt_points, nb_E,
			verbose_level);

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"after Surf_arc->classify_surfaces_through_arcs_and_trihedral_pairs" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"before Surf_arc->report" << endl;
	}


	if (The_Orbiter_session->f_draw_options) {
		Surf_arc->report(The_Orbiter_session->draw_options, verbose_level);
	}
	else {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"please use -draw_option for a report" << endl;
	}

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs "
				"after Surf_arc->report" << endl;
	}

	FREE_OBJECT(Surf_arc);

	if (f_v) {
		cout << "group_theoretic_activity::do_classify_surfaces_through_arcs_and_trihedral_pairs done" << endl;
	}

}

void group_theoretic_activity::do_six_arcs(
		poset_classification_control *Control_six_arcs,
		int f_filter_by_nb_Eckardt_points, int nb_Eckardt_points,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs" << endl;
	}

	finite_field *F;

	F = LG->F;


	surface_domain *Surf;

	if (f_v) {
			cout << "group_theoretic_activity::do_six_arcs before Surf->init" << endl;
	}
	Surf = NEW_OBJECT(surface_domain);
	Surf->init(F, 0/*verbose_level - 1*/);
	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs after Surf->init" << endl;
	}



	six_arcs_not_on_a_conic *Six_arcs;
	arc_generator_description *Six_arc_descr;

	int *transporter;

	Six_arcs = NEW_OBJECT(six_arcs_not_on_a_conic);

	Six_arc_descr = NEW_OBJECT(arc_generator_description);
	Six_arc_descr->F = F;
	Six_arc_descr->f_q = TRUE;
	Six_arc_descr->q = F->q;
	Six_arc_descr->f_n = TRUE;
	Six_arc_descr->n = 3;
	Six_arc_descr->f_target_size = TRUE;
	Six_arc_descr->target_size = 6;
	Six_arc_descr->Control = Control_six_arcs;



	// classify six arcs not on a conic:

	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs "
				"Setting up the group of the plane:" << endl;
	}



	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs "
				"before Six_arcs->init:" << endl;
	}


	Six_arcs->init(
			Six_arc_descr,
			LG->A_linear,
			Surf->P2,
			FALSE, 0, NULL,
			verbose_level);

	transporter = NEW_int(Six_arcs->Gen->A->elt_size_in_int);

	int nb_orbits;
	int level = 6;

	nb_orbits = Six_arcs->Gen->gen->nb_orbits_at_level(level);

	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs "
				"We found " << nb_orbits << " isomorphism types "
				"of 6-arcs" << endl;
	}



	long int Arc6[6];
	int h, a, b, c, d;
	int v1[3];
	int v2[3];


	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs "
				"testing the arcs" << endl;
	}

	longinteger_object ago;
	int *Abcd;
	int *Nb_E;
	int *Ago;

	Abcd = NEW_int(nb_orbits * 4);
	Nb_E = NEW_int(nb_orbits);
	Ago = NEW_int(nb_orbits);

	for (h = 0; h < nb_orbits; h++) {

		if (f_v) {
			cout << "group_theoretic_activity::do_six_arcs "
					"testing arc " << h << " / " << nb_orbits << endl;
		}


		Six_arcs->Gen->gen->get_set_by_level(level, h, Arc6);

		Six_arcs->Gen->gen->get_stabilizer_order(level, h, ago);

		if (Arc6[0] != 0) {
			cout << "Arc6[0] != 0" << endl;
			exit(1);
		}
		if (Arc6[1] != 1) {
			cout << "Arc6[1] != 1" << endl;
			exit(1);
		}
		if (Arc6[2] != 2) {
			cout << "Arc6[2] != 2" << endl;
			exit(1);
		}
		if (Arc6[3] != 3) {
			cout << "Arc6[3] != 3" << endl;
			exit(1);
		}
		Surf->P2->unrank_point(v1, Arc6[4]);
		Surf->P2->unrank_point(v2, Arc6[5]);
		if (v1[2] != 1) {
			cout << "v1[2] != 1" << endl;
			exit(1);
		}
		if (v2[2] != 1) {
			cout << "v2[2] != 1" << endl;
			exit(1);
		}
		a = v1[0];
		b = v1[1];
		c = v2[0];
		d = v2[1];

		Abcd[h * 4 + 0] = a;
		Abcd[h * 4 + 1] = b;
		Abcd[h * 4 + 2] = c;
		Abcd[h * 4 + 3] = d;

		eckardt_point_info *E;

		E = Surf->P2->compute_eckardt_point_info(Surf, Arc6, 0/*verbose_level*/);


		Nb_E[h] = E->nb_E;
		Ago[h] = ago.as_int();

		//cout << h << " : " << a << "," << b << "," << c << "," << d << " : " << E->nb_E << " : " << ago << endl;

		FREE_OBJECT(E);
	}

#if 0
	cout << "Summary of " << nb_orbits << " arcs:" << endl;
	for (h = 0; h < nb_orbits; h++) {
		a = Abcd[h * 4 + 0];
		b = Abcd[h * 4 + 1];
		c = Abcd[h * 4 + 2];
		d = Abcd[h * 4 + 3];

		cout << h << " : " << a << "," << b << "," << c << "," << d << " : " << Nb_E[h] << " : " << Ago[h] << endl;
	}
#endif

	tally C;

	C.init(Nb_E, nb_orbits, FALSE, 0);

	cout << "nb_E distribution: ";
	C.print_naked_tex(cout, FALSE);
	cout << endl;


	if (f_filter_by_nb_Eckardt_points) {
		cout << "Nonconical six-arcs associated with surfaces with " << nb_Eckardt_points << " Eckardt points in PG(2," << F->q << "):" << endl;

	}
	else {
		cout << "Nonconical six-arcs associated in PG(2," << F->q << "):" << endl;

	}
	int nb_E;
	int cnt = 0;

	cout << "$$" << endl;
	cout << "\\begin{array}{|r|c|r|}" << endl;
	cout << "\\hline" << endl;
	cout << "\\mbox{Orbit} & a,b,c,d & \\mbox{Ago} \\\\" << endl;
	cout << "\\hline" << endl;

	for (h = 0; h < nb_orbits; h++) {
		a = Abcd[h * 4 + 0];
		b = Abcd[h * 4 + 1];
		c = Abcd[h * 4 + 2];
		d = Abcd[h * 4 + 3];

		nb_E = Nb_E[h];

		if (f_filter_by_nb_Eckardt_points) {
			if (nb_E != nb_Eckardt_points) {
				continue;
			}
		}
		cout << h << " & " << a << "," << b << "," << c << "," << d << " & ";
		//<< Nb_E[h] << " & "
		cout << Ago[h] << "\\\\" << endl;

		cnt++;
	}
	cout << "\\hline" << endl;
	cout << "\\end{array}" << endl;
	cout << "$$" << endl;
	cout << "There are " << cnt << " such arcs.\\\\" << endl;


	FREE_int(Abcd);
	FREE_int(Nb_E);
	FREE_int(Ago);


	FREE_OBJECT(Six_arcs);
	FREE_OBJECT(Six_arc_descr);
	FREE_int(transporter);


	if (f_v) {
		cout << "group_theoretic_activity::do_six_arcs done" << endl;
	}

}


}}

