/*
 * orthogonal_space_activity.cpp
 *
 *  Created on: Jan 12, 2021
 *      Author: betten
 */




#include "orbiter.h"

using namespace std;

namespace orbiter {
namespace top_level {


orthogonal_space_activity::orthogonal_space_activity()
{
	Descr = NULL;
	OA = NULL;
	Blt_set_domain = NULL;

}

orthogonal_space_activity::~orthogonal_space_activity()
{
	if (Blt_set_domain) {
		FREE_OBJECT(Blt_set_domain);
	}
	if (OA) {
		FREE_OBJECT(OA);
	}
}

void orthogonal_space_activity::init(orthogonal_space_activity_description *Descr,
		orthogonal_space_with_action *OA,
		int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "orthogonal_space_activity::init" << endl;
	}

	orthogonal_space_activity::Descr = Descr;
	orthogonal_space_activity::OA = OA;



	if (f_v) {
		cout << "orthogonal_space_activity::init done" << endl;
	}
}


void orthogonal_space_activity::perform_activity(int verbose_level)
{
	int f_v = (verbose_level >= 1);

	if (f_v) {
		cout << "orthogonal_space_activity::perform_activity" << endl;
	}

	if (Descr->f_cheat_sheet_orthogonal) {

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity before OA->report" << endl;
		}

		if (!Orbiter->f_draw_options) {
			cout << "please use -draw_options ... -end" << endl;
			exit(1);
		}

		OA->report(Orbiter->draw_options,
				verbose_level);


		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity after OA->report" << endl;
		}

	}

	else if (Descr->f_unrank_line_through_two_points) {

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_unrank_line_through_two_points" << endl;
		}

		long int p1;
		long int p2;
		long int rk;

		p1 = strtolint(Descr->unrank_line_through_two_points_p1);
		p2 = strtolint(Descr->unrank_line_through_two_points_p2);

		cout << "point rank p1 = " << p1 << endl;
		cout << "point rank p2 = " << p2 << endl;

		rk = OA->O->rank_line(p1, p2, verbose_level);

		cout << "line rank = " << rk << endl;

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_unrank_line_through_two_points done" << endl;
		}

	}

	else if (Descr->f_lines_on_point) {

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_lines_on_point" << endl;
		}

		long int *line_pencil_line_ranks;

		line_pencil_line_ranks = NEW_lint(OA->O->alpha);

		cout << "point rank = " << Descr->lines_on_point_rank << endl;

		OA->O->lines_on_point_by_line_rank(Descr->lines_on_point_rank,
				line_pencil_line_ranks, verbose_level);

		cout << "There are " << OA->O->alpha << " lines on point = "
				<< Descr->lines_on_point_rank << ". They are: ";
		Orbiter->Lint_vec.print_fully(cout, line_pencil_line_ranks, OA->O->alpha);
		cout << endl;

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_lines_on_point done" << endl;
		}

	}

	else if (Descr->f_perp) {

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_perp" << endl;
		}

		long int *pts;
		int nb_pts;

		Orbiter->Lint_vec.scan(Descr->perp_text.c_str(), pts, nb_pts);

		cout << "Computing the common perp of the set ";
		Orbiter->Lint_vec.print(cout, pts, nb_pts);
		cout << endl;

		long int *Perp;
		int sz;


		OA->O->perp_of_k_points(pts, nb_pts, Perp, sz, verbose_level);

		cout << "The common perp of the set has size " << sz << " and is ";
		Orbiter->Lint_vec.print_fully(cout, Perp, sz);
		cout << endl;

		FREE_lint(Perp);
		FREE_lint(pts);

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_perp done" << endl;
		}

	}

	else if (Descr->f_create_BLT_set) {

		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_create_BLT_set" << endl;
		}


		Blt_set_domain = NEW_OBJECT(blt_set_domain);

		if (f_v) {
			cout << "BLT_set_create::init before Blt_set_domain->init" << endl;
		}
		Blt_set_domain->init(OA->O, verbose_level);
		if (f_v) {
			cout << "BLT_set_create::init after Blt_set_domain->init" << endl;
		}

		BLT_set_create *BC;

		BC = NEW_OBJECT(BLT_set_create);

		BC->init(Blt_set_domain, Descr->BLT_Set_create_description, OA, verbose_level);

		latex_interface L;


		cout << "We have created the following BLT-set:" << endl;
		cout << "$$" << endl;
		L.lint_set_print_tex(cout, BC->set, OA->Descr->F->q + 1);
		cout << endl;
		cout << "$$" << endl;

		if (BC->f_has_group) {
			cout << "The stabilizer is generated by:" << endl;
			BC->Sg->print_generators_tex(cout);
		}

		BC->report(verbose_level);

		FREE_OBJECT(BC);


		if (f_v) {
			cout << "orthogonal_space_activity::perform_activity f_create_BLT_set done" << endl;
		}

	}



	if (f_v) {
		cout << "orthogonal_space_activity::perform_activity done" << endl;
	}

}


}}
