all: ;
	cd ARCS; $(MAKE) all
	cd BLT; $(MAKE) all
	cd CODES; $(MAKE) all
	cd COMBINATORICS; $(MAKE) all
	cd GRAPH; $(MAKE) all
	cd GROUPS; $(MAKE) all
	cd OVOID; $(MAKE) all
	cd PROJECTIVE_SPACE; $(MAKE) all
	cd REGULAR_LS; $(MAKE) all
	cd SPREAD; $(MAKE) all
	cd SUBSPACE_ORBITS; $(MAKE) all
	cd SURFACES; $(MAKE) all
	cd TDO; $(MAKE) all
	cd TOOLS; $(MAKE) all

clean: ;
	cd ARCS; $(MAKE) clean
	cd BLT; $(MAKE) clean
	cd CODES; $(MAKE) clean
	cd COMBINATORICS; $(MAKE) clean
	cd GRAPH; $(MAKE) clean
	cd GROUPS; $(MAKE) clean
	cd OVOID; $(MAKE) clean
	cd PROJECTIVE_SPACE; $(MAKE) clean
	cd REGULAR_LS; $(MAKE) clean
	cd SPREAD; $(MAKE) clean
	cd SUBSPACE_ORBITS; $(MAKE) clean
	cd SURFACES; $(MAKE) clean
	cd TDO; $(MAKE) clean
	cd TOOLS; $(MAKE) clean

