all: 
	cd algebra; $(MAKE) all
	cd arcs; $(MAKE) all
	cd blt; $(MAKE) all
	cd codes; $(MAKE) all
	cd combinatorics; $(MAKE) all
	cd graph; $(MAKE) all
	cd graph_theory; $(MAKE) all
	cd groups; $(MAKE) all
	cd linear_spaces; $(MAKE) all
	#cd main; $(MAKE) all
	cd ovoid; $(MAKE) all
	cd projective_space; $(MAKE) all
	cd regular_ls; $(MAKE) all
	cd solver; $(MAKE) all
	cd spread; $(MAKE) all
	cd subspace_orbits; $(MAKE) all
	cd surfaces; $(MAKE) all
	cd test; $(MAKE) all
	cd tools; $(MAKE) all

clean: 
	cd algebra; $(MAKE) clean
	cd arcs; $(MAKE) clean
	cd blt; $(MAKE) clean
	cd codes; $(MAKE) clean
	cd combinatorics; $(MAKE) clean
	cd graph; $(MAKE) clean
	cd graph_theory; $(MAKE) clean
	cd groups; $(MAKE) clean
	cd linear_spaces; $(MAKE) clean
	cd main; $(MAKE) clean
	cd ovoid; $(MAKE) clean
	cd projective_space; $(MAKE) clean
	cd regular_ls; $(MAKE) clean
	cd solver; $(MAKE) clean
	cd spread; $(MAKE) clean
	cd subspace_orbits; $(MAKE) clean
	cd surfaces; $(MAKE) clean
	cd test; $(MAKE) clean
	cd tools; $(MAKE) clean

