MY_PATH=~/DEV.20/GITHUB/orbiter

ORBITER_PATH=$(MY_PATH)/src/apps/orbiter



CRC_2_4_4:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 4 4 -end

CRC_2_5_4:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 5 4 -end

CRC_2_6_4:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 6 4 -end

CRC_2_7_4:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 7 4 -end

CRC_2_8_4:
	$(ORBITER_PATH)/orbiter.out -v 2 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 8 4 -end

CRC_2_9_4:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 9 4 -end

CRC_2_9_5:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 9 5 -end

CRC_2_10_5:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 10 5 -end

CRC_2_32_6:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 32 6 -end

CRC_2_64_8:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 64 8 -end

CRC_2_128_8:
	$(ORBITER_PATH)/orbiter.out -v 1 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 128 8 -end

CRC_3_128_8:
	$(ORBITER_PATH)/orbiter.out -v 1 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 128 8 -end

CRC_3_128_10:
	$(ORBITER_PATH)/orbiter.out -v 1 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 128 10 -end



CRC_2_256_8:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 256 8 -end


CRC_2_256_12:
	$(ORBITER_PATH)/orbiter.out -v 1 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 2 256 12 -end

CRC_3_256_8:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 256 8 -end

CRC_3_256_16:
	$(ORBITER_PATH)/orbiter.out -v 1 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 256 16 -end



CRC_3_8_4:
	$(ORBITER_PATH)/orbiter.out -v 2 -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 8 4 -end



CRC_3_64_8:
	$(ORBITER_PATH)/orbiter.out -define F -finite_field -q 2 -end -end \
		-with F -do -finite_field_activity -find_CRC_polynomials 3 64 8 -end









