% file: graphs_v5_rep_5_0.mp
% created by Orbiter metapost interface
% creation date: Sat Jul 30 08:11:07 +03 2022

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
pickup pencircle scaled 1pt;
draw (850u ,500u )--(608.1u ,832.8u );
draw (850u ,500u )--(216.9u ,705.7u );
draw (850u ,500u )--(216.9u ,294.3u );
draw (850u ,500u )--(608.1u ,167.2u );
draw (608.1u ,832.8u )--(216.9u ,705.7u );
path pp;
pp = (880u ,500u ) .. (850u ,530u ) .. (820u ,500u ) .. (850u ,470u ) .. (880u ,500u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (880u ,500u ) .. (850u ,530u ) .. (820u ,500u ) .. (850u ,470u ) .. (880u ,500u ) .. cycle;
draw pp;
path pp;
pp = (638.1u ,832.8u ) .. (608.1u ,862.8u ) .. (578.1u ,832.8u ) .. (608.1u ,802.8u ) .. (638.1u ,832.8u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (638.1u ,832.8u ) .. (608.1u ,862.8u ) .. (578.1u ,832.8u ) .. (608.1u ,802.8u ) .. (638.1u ,832.8u ) .. cycle;
draw pp;
path pp;
pp = (246.9u ,705.7u ) .. (216.9u ,735.7u ) .. (186.9u ,705.7u ) .. (216.9u ,675.7u ) .. (246.9u ,705.7u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (246.9u ,705.7u ) .. (216.9u ,735.7u ) .. (186.9u ,705.7u ) .. (216.9u ,675.7u ) .. (246.9u ,705.7u ) .. cycle;
draw pp;
path pp;
pp = (246.9u ,294.3u ) .. (216.9u ,324.3u ) .. (186.9u ,294.3u ) .. (216.9u ,264.3u ) .. (246.9u ,294.3u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (246.9u ,294.3u ) .. (216.9u ,324.3u ) .. (186.9u ,294.3u ) .. (216.9u ,264.3u ) .. (246.9u ,294.3u ) .. cycle;
draw pp;
path pp;
pp = (638.1u ,167.2u ) .. (608.1u ,197.2u ) .. (578.1u ,167.2u ) .. (608.1u ,137.2u ) .. (638.1u ,167.2u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (638.1u ,167.2u ) .. (608.1u ,197.2u ) .. (578.1u ,167.2u ) .. (608.1u ,137.2u ) .. (638.1u ,167.2u ) .. cycle;
draw pp;
endfig;

end

