% file: tournament_4_rep_6_1.mp
% created by Orbiter metapost interface
% creation date: Sat Jul 30 08:28:14 +03 2022

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
drawarrow (850u ,500u )--(587.5u ,762.5u );
drawarrow (850u ,500u )--(325u ,500u );
drawarrow (850u ,500u )--(587.5u ,237.5u );
drawarrow (500u ,850u )--(237.5u ,587.5u );
drawarrow (500u ,150u )--(500u ,675u );
drawarrow (150u ,500u )--(412.5u ,237.5u );
path pp;
pp = (890u ,500u ) .. (850u ,540u ) .. (810u ,500u ) .. (850u ,460u ) .. (890u ,500u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (890u ,500u ) .. (850u ,540u ) .. (810u ,500u ) .. (850u ,460u ) .. (890u ,500u ) .. cycle;
draw pp;
path pp;
pp = (540u ,850u ) .. (500u ,890u ) .. (460u ,850u ) .. (500u ,810u ) .. (540u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (540u ,850u ) .. (500u ,890u ) .. (460u ,850u ) .. (500u ,810u ) .. (540u ,850u ) .. cycle;
draw pp;
path pp;
pp = (190u ,500u ) .. (150u ,540u ) .. (110u ,500u ) .. (150u ,460u ) .. (190u ,500u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (190u ,500u ) .. (150u ,540u ) .. (110u ,500u ) .. (150u ,460u ) .. (190u ,500u ) .. cycle;
draw pp;
path pp;
pp = (540u ,150u ) .. (500u ,190u ) .. (460u ,150u ) .. (500u ,110u ) .. (540u ,150u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (540u ,150u ) .. (500u ,190u ) .. (460u ,150u ) .. (500u ,110u ) .. (540u ,150u ) .. cycle;
draw pp;
endfig;

end

