all: 
	cd mckay; $(MAKE) all
	cd orbiter; $(MAKE) all
	cd sandbox; $(MAKE) all
	

clean: 
	cd mckay; $(MAKE) clean
	cd orbiter; $(MAKE) clean
	cd sandbox; $(MAKE) clean

install: 
	cd mckay; $(MAKE) install
	cd orbiter; $(MAKE) install
	cd sandbox; $(MAKE) install

