all: 
	cd arcs; $(MAKE) all
	cd blt; $(MAKE) all
	#cd main; $(MAKE) all
	cd orbiter; $(MAKE) all
	cd packing; $(MAKE) all
	cd subspace_orbits; $(MAKE) all
	cd surfaces; $(MAKE) all
	cd tools; $(MAKE) all
	#cd ginac; $(MAKE) all
		# ginac requires cln and ginac to be installed

clean: 
	cd arcs; $(MAKE) clean
	cd blt; $(MAKE) clean
	cd ginac; $(MAKE) clean
	cd main; $(MAKE) clean
	cd orbiter; $(MAKE) clean
	cd packing; $(MAKE) clean
	cd subspace_orbits; $(MAKE) clean
	cd surfaces; $(MAKE) clean
	cd tools; $(MAKE) clean

install: 
	cd arcs; $(MAKE) install
	cd blt; $(MAKE) install
	#cd main; $(MAKE) install
	cd orbiter; $(MAKE) install
	cd packing; $(MAKE) install
	cd subspace_orbits; $(MAKE) install
	cd surfaces; $(MAKE) install
	cd tools; $(MAKE) install

