all: 
	cd arcs; $(MAKE) all
	cd orbiter; $(MAKE) all
	#cd ginac; $(MAKE) all
		# ginac requires cln and ginac to be installed

clean: 
	cd arcs; $(MAKE) clean
	cd ginac; $(MAKE) clean
	cd orbiter; $(MAKE) clean

install: 
	cd arcs; $(MAKE) install
	cd orbiter; $(MAKE) install

