all:
	~/bin/a2tex.out -numbers <cube.txt >cube.tex
	~/bin/a2tex.out -numbers <monkey.txt >monkey.tex
	~/bin/a2tex.out -numbers <HCV.txt >HCV.tex
	~/bin/a2tex.out -numbers <lissajous.txt >lissajous.tex
	~/bin/a2tex.out -numbers <lissajous_3d.txt >lissajous_3d.tex

