%
% created by a2tex
%
\begin{tabbing}
55555: \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= 55 \= \kill
1\>MY\_PATH=\symbol{126}/DEV\symbol{46}20/GITHUB/orbiter\\[0pt]
2\>ORBITER\_PATH=\symbol{36}(MY\_PATH)/src/apps/orbiter\\[0pt]
3\>\\[0pt]
4\>PG\_2\_16:\\[0pt]
5\>\>\symbol{36}(ORBITER\_PATH)/orbiter\symbol{46}out\ \symbol{45}cheat\_sheet\_PG\ 2\ 16\\[0pt]
6\>\>pdflatex\ PG\_2\_16\symbol{46}tex\ \\[0pt]
7\>\>open\ PG\_2\_16\symbol{46}pdf\\[0pt]
8\>\\[0pt]
9\>\end{tabbing}
