/*
 * design_create_main.cpp
 *
 *  Created on: Sep 19, 2019
 *      Author: betten
 */


#include "orbiter.h"

using namespace std;


using namespace orbiter;
using namespace orbiter::top_level;

// global data:

int t0; // the system time when the program started

int main(int argc, const char **argv);

int main(int argc, const char **argv)
{
	int verbose_level = 0;
	int i;
	int f_design = FALSE;
	design_create_description *Descr;
	int f_depth = FALSE;
	int depth = 0;
	int f_output_prefix = FALSE;
	const char *output_prefix = "";

	t0 = os_ticks();


	for (i = 1; i < argc; i++) {
		if (strcmp(argv[i], "-v") == 0) {
			verbose_level = atoi(argv[++i]);
			cout << "-v " << verbose_level << endl;
		}
		else if (strcmp(argv[i], "-design") == 0) {
			f_design = TRUE;
			Descr = NEW_OBJECT(design_create_description);
			i += Descr->read_arguments(argc - (i - 1),
					argv + i, verbose_level) - 1;

			cout << "-design" << endl;
		}
		else if (strcmp(argv[i], "-depth") == 0) {
			f_depth = TRUE;
			depth = atoi(argv[++i]);
			cout << "-depth " << depth << endl;
		}
		else if (strcmp(argv[i], "-output_prefix") == 0) {
			f_output_prefix = TRUE;
			output_prefix = argv[++i];
			cout << "-output_prefix " << output_prefix << endl;
		}
	}
	if (!f_design) {
		cout << "please use option -design ... "
				"to enter a description of the design" << endl;
		exit(1);
	}

	design_create *DC;
	//int j;

	DC = NEW_OBJECT(design_create);

	cout << "before DC->init" << endl;
	DC->init(Descr, verbose_level);
	cout << "after DC->init" << endl;



	action *A;
	//int *Elt1;
	int *Elt2;

	A = DC->A;

	Elt2 = NEW_int(A->elt_size_in_int);



#if 0
	if (DC->f_has_group) {
		for (i = 0; i < BC->Sg->gens->len; i++) {
			cout << "Testing generator " << i << " / "
					<< BC->Sg->gens->len << endl;
			A->element_invert(BC->Sg->gens->ith(i),
					Elt2, 0 /*verbose_level*/);


			cout << "Generator " << i << " / " << SC->Sg->gens->len
					<< " is good" << endl;
			}
		}
	else {
		cout << "We do not have information about the "
				"automorphism group" << endl;
		}
#endif


	cout << "We have created the following design:" << endl;
	cout << "$$" << endl;
	int_set_print_tex(cout, DC->set, DC->sz);
	cout << endl;
	cout << "$$" << endl;

	if (DC->f_has_group) {
		cout << "The stabilizer is generated by:" << endl;
		DC->Sg->print_generators_tex(cout);
		}


	orbit_of_sets *SetOrb;

	SetOrb = NEW_OBJECT(orbit_of_sets);

	cout << "computing orbit:" << endl;
	SetOrb->init(DC->A, DC->A2,
			DC->set, DC->sz, DC->A->Strong_gens->gens,
			verbose_level);
	cout << "computing orbit done" << endl;


	large_set_classify *LS;

	LS = NEW_OBJECT(large_set_classify);

	int f_lexorder_test = TRUE;
	char base_fname[1000];
	const char *design_tables_prefix = "";

	sprintf(base_fname, "LS_%s", DC->prefix);
	LS->init(DC,
			output_prefix, base_fname,
			depth,
			f_lexorder_test,
			design_tables_prefix,
			verbose_level);

	LS->init_designs(SetOrb, verbose_level);

	if (f_depth) {
		cout << "depth = " << depth << endl;
		LS->gen->depth = depth;

		LS->compute(verbose_level);
	}

	FREE_int(Elt2);

	FREE_OBJECT(DC);

	the_end(t0);
	//the_end_quietly(t0);
}




