var searchData=
[
  ['data_5ffile',['data_file',['../d2/dd1/classdata__file.html',1,'']]],
  ['database',['database',['../db/d72/classdatabase.html',1,'']]],
  ['datatype',['datatype',['../d6/d22/structdatatype.html',1,'']]],
  ['decomposition',['decomposition',['../d3/d2b/classdecomposition.html',1,'']]],
  ['desarguesian_5fspread',['desarguesian_spread',['../d4/d86/classdesarguesian__spread.html',1,'']]],
  ['design_5fdata',['design_data',['../d3/dbe/structdesign__data.html',1,'']]],
  ['design_5fparameter',['design_parameter',['../da/d94/classdesign__parameter.html',1,'']]],
  ['design_5fparameter_5fsource',['design_parameter_source',['../df/d4b/classdesign__parameter__source.html',1,'']]],
  ['difference_5fset_5fin_5fheisenberg_5fgroup',['difference_set_in_heisenberg_group',['../de/d8a/classdifference__set__in__heisenberg__group.html',1,'']]],
  ['diophant',['diophant',['../d7/d9c/classdiophant.html',1,'']]],
  ['direct_5fproduct',['direct_product',['../dc/daf/classdirect__product.html',1,'']]],
  ['direct_5fproduct_5faction',['direct_product_action',['../d3/d78/classdirect__product__action.html',1,'']]],
  ['discreta_5fbase',['discreta_base',['../d7/d71/classdiscreta__base.html',1,'']]],
  ['dispatchvec',['dispatchvec',['../d7/df1/structdispatchvec.html',1,'']]],
  ['dlx_5fnode',['dlx_node',['../da/d66/structdlx__node.html',1,'']]],
  ['domain',['domain',['../de/d3b/classdomain.html',1,'']]],
  ['dynamic_5fmemory',['dynamic_memory',['../df/db6/classdynamic__memory.html',1,'']]]
];
