var searchData=
[
  ['data_2ec',['data.C',['../d7/d94/data_8_c.html',1,'']]],
  ['data_5fblt_2ec',['data_BLT.C',['../d4/dfc/data___b_l_t_8_c.html',1,'']]],
  ['data_5fdh_2ec',['data_DH.C',['../d8/db3/data___d_h_8_c.html',1,'']]],
  ['data_5ffile_2ec',['data_file.C',['../da/d9a/data__file_8_c.html',1,'']]],
  ['data_5fhyperovals_2ec',['data_hyperovals.C',['../d2/d91/data__hyperovals_8_c.html',1,'']]],
  ['data_5fpackings_5fpg_5f3_5f3_2ec',['data_packings_PG_3_3.C',['../d6/d1e/data__packings___p_g__3__3_8_c.html',1,'']]],
  ['data_5fspreads_2ec',['data_spreads.C',['../d2/da1/data__spreads_8_c.html',1,'']]],
  ['data_5fstructures_2eh',['data_structures.h',['../d5/de2/foundations_2data__structures_2data__structures_8h.html',1,'(Global Namespace)'],['../dc/d9b/groups__and__group__actions_2data__structures_2data__structures_8h.html',1,'(Global Namespace)']]],
  ['database_2ec',['database.C',['../d1/d1f/database_8_c.html',1,'']]],
  ['decomposition_2ec',['decomposition.C',['../d6/d7a/foundations_2geometry_2decomposition_8_c.html',1,'(Global Namespace)'],['../db/d10/top__level_2geometry_2decomposition_8_c.html',1,'(Global Namespace)']]],
  ['desarguesian_5fspread_2ec',['desarguesian_spread.C',['../d5/dd7/apps_2subspace__orbits_2desarguesian__spread_8_c.html',1,'(Global Namespace)'],['../de/d46/lib_2foundations_2geometry_2desarguesian__spread_8_c.html',1,'(Global Namespace)']]],
  ['design_2ec',['design.C',['../d9/dc2/apps_2combinatorics_2design_8_c.html',1,'(Global Namespace)'],['../d1/dec/lib_2_d_i_s_c_r_e_t_a_2design_8_c.html',1,'(Global Namespace)']]],
  ['design_5fparameter_2ec',['design_parameter.C',['../d3/d56/design__parameter_8_c.html',1,'']]],
  ['design_5fparameter_5fsource_2ec',['design_parameter_source.C',['../d5/dba/design__parameter__source_8_c.html',1,'']]],
  ['determine_5fconic_2ec',['determine_conic.C',['../de/d27/determine__conic_8_c.html',1,'']]],
  ['determine_5fquadric_2ec',['determine_quadric.C',['../d7/d9d/determine__quadric_8_c.html',1,'']]],
  ['diophant_2ec',['diophant.C',['../dc/dfe/diophant_8_c.html',1,'']]],
  ['direct_5fproduct_2ec',['direct_product.C',['../d1/d9d/apps_2groups_2direct__product_8_c.html',1,'(Global Namespace)'],['../d6/df7/lib_2groups__and__group__actions_2group__theory_2direct__product_8_c.html',1,'(Global Namespace)']]],
  ['discreta_2eh',['discreta.h',['../d9/d60/discreta_8h.html',1,'']]],
  ['discreta_5fglobal_2ec',['discreta_global.C',['../d3/dfb/discreta__global_8_c.html',1,'']]],
  ['distribution_2ec',['distribution.C',['../df/da4/distribution_8_c.html',1,'']]],
  ['dlx_2ec',['dlx.C',['../dc/d57/apps_2tools_2dlx_8_c.html',1,'(Global Namespace)'],['../d9/d5e/lib_2foundations_2solvers_2dlx_8_c.html',1,'(Global Namespace)']]],
  ['domain_2ec',['domain.C',['../db/d2f/domain_8_c.html',1,'']]],
  ['draw_2ec',['draw.C',['../d9/d29/draw_8_c.html',1,'']]],
  ['draw_5fcolored_5fgraph_2ec',['draw_colored_graph.C',['../d2/dfa/draw__colored__graph_8_c.html',1,'']]],
  ['draw_5fgraph_2ec',['draw_graph.C',['../d4/da5/draw__graph_8_c.html',1,'']]],
  ['dynamic_5fmemory_2ec',['dynamic_memory.C',['../d3/d77/dynamic__memory_8_c.html',1,'']]]
];
