var searchData=
[
  ['packing_2ec',['packing.C',['../d4/ddd/apps_2tdo_2packing_8_c.html',1,'(Global Namespace)'],['../de/d59/lib_2foundations_2geometry_2packing_8_c.html',1,'(Global Namespace)']]],
  ['page_5fstorage_2ec',['page_storage.C',['../db/d3c/page__storage_8_c.html',1,'']]],
  ['page_5ftable_2ec',['page_table.C',['../d7/df5/page__table_8_c.html',1,'']]],
  ['paley_2ec',['paley.C',['../d8/dae/paley_8_c.html',1,'']]],
  ['partitions_2ec',['partitions.C',['../d0/df7/partitions_8_c.html',1,'']]],
  ['partitionstack_2ec',['partitionstack.C',['../d0/d1b/partitionstack_8_c.html',1,'']]],
  ['pentomino_5f5x5_2ec',['pentomino_5x5.C',['../dc/d77/pentomino__5x5_8_c.html',1,'']]],
  ['perm_5fgroup_2ec',['perm_group.C',['../db/d7c/perm__group_8_c.html',1,'']]],
  ['perm_5fgroup_5fgens_2ec',['perm_group_gens.C',['../d0/dd3/perm__group__gens_8_c.html',1,'']]],
  ['permutation_2ec',['permutation.C',['../d9/d33/permutation_8_c.html',1,'']]],
  ['plane_5fsearch_2ec',['plane_search.C',['../dd/d07/plane__search_8_c.html',1,'']]],
  ['plot_2ec',['plot.C',['../de/dea/plot_8_c.html',1,'']]],
  ['plot_5fdecomposition_5fmatrix_2ec',['plot_decomposition_matrix.C',['../d6/d34/plot__decomposition__matrix_8_c.html',1,'']]],
  ['plot_5fstats_5fon_5fgraphs_2ec',['plot_stats_on_graphs.C',['../d6/d80/plot__stats__on__graphs_8_c.html',1,'']]],
  ['plot_5fxy_2ec',['plot_xy.C',['../d5/dba/plot__xy_8_c.html',1,'']]],
  ['point_5fline_2ec',['point_line.C',['../d0/d75/point__line_8_c.html',1,'']]],
  ['points_2ec',['points.C',['../d7/d83/points_8_c.html',1,'']]],
  ['polar_2ec',['polar.C',['../d5/d0d/apps_2projective__space_2polar_8_c.html',1,'(Global Namespace)'],['../d4/dc2/lib_2top__level_2geometry_2polar_8_c.html',1,'(Global Namespace)']]],
  ['poset_5fclassification_2eh',['poset_classification.h',['../da/d69/poset__classification_8h.html',1,'']]],
  ['poset_5fof_5fsubsets_2ec',['poset_of_subsets.C',['../da/d78/poset__of__subsets_8_c.html',1,'']]],
  ['prepare_5fframes_2ec',['prepare_frames.C',['../dc/d2b/prepare__frames_8_c.html',1,'']]],
  ['problem11_2ec',['problem11.C',['../d6/d9f/problem11_8_c.html',1,'']]],
  ['process_2ec',['process.C',['../d0/d2f/process_8_c.html',1,'']]],
  ['process_5fpg_2ec',['process_PG.C',['../d7/d29/process___p_g_8_c.html',1,'']]],
  ['product_5faction_2ec',['product_action.C',['../dc/d39/product__action_8_c.html',1,'']]],
  ['projective_2ec',['projective.C',['../df/de4/projective_8_c.html',1,'']]],
  ['projective_5fspace_2ec',['projective_space.C',['../d1/dbe/foundations_2geometry_2projective__space_8_c.html',1,'(Global Namespace)'],['../d6/de8/top__level_2geometry_2projective__space_8_c.html',1,'(Global Namespace)']]],
  ['projective_5fspace_5fmain_2ec',['projective_space_main.C',['../d0/de6/projective__space__main_8_c.html',1,'']]],
  ['projective_5fspace_5fwith_5faction_2ec',['projective_space_with_action.C',['../d0/daa/projective__space__with__action_8_c.html',1,'']]],
  ['puzzle_2ec',['puzzle.C',['../d6/d12/puzzle_8_c.html',1,'']]]
];
