% file: PGGL_2_8_OnConic_sims_0.mp
% created by Orbiter metapost interface
% creation date: Sat Dec 19 23:54:03 MST 2020

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
draw (500u ,958.3u )--(500u ,875u );
draw (500u ,875u )--(500u ,791.6u );
draw (500u ,791.6u )--(416.6u ,708.3u );
draw (500u ,791.6u )--(916.6u ,708.3u );
draw (416.6u ,708.3u )--(208.3u ,625u );
draw (416.6u ,708.3u )--(625u ,625u );
draw (208.3u ,625u )--(208.3u ,541.6u );
draw (625u ,625u )--(625u ,541.6u );
path pp;
pp = (525u ,958.3u ) .. (500u ,983.3u ) .. (475u ,958.3u ) .. (500u ,933.3u ) .. (525u ,958.3u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (525u ,958.3u ) .. (500u ,983.3u ) .. (475u ,958.3u ) .. (500u ,933.3u ) .. (525u ,958.3u ) .. cycle;
draw pp;
label(btex {\scriptsize 0} etex, (500u ,958.3u ));
path pp;
pp = (525u ,875u ) .. (500u ,900u ) .. (475u ,875u ) .. (500u ,850u ) .. (525u ,875u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (525u ,875u ) .. (500u ,900u ) .. (475u ,875u ) .. (500u ,850u ) .. (525u ,875u ) .. cycle;
draw pp;
label(btex {\scriptsize 1} etex, (500u ,875u ));
path pp;
pp = (525u ,791.6u ) .. (500u ,816.6u ) .. (475u ,791.6u ) .. (500u ,766.6u ) .. (525u ,791.6u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (525u ,791.6u ) .. (500u ,816.6u ) .. (475u ,791.6u ) .. (500u ,766.6u ) .. (525u ,791.6u ) .. cycle;
draw pp;
label(btex {\scriptsize 5} etex, (500u ,791.6u ));
path pp;
pp = (441.6u ,708.3u ) .. (416.6u ,733.3u ) .. (391.6u ,708.3u ) .. (416.6u ,683.3u ) .. (441.6u ,708.3u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (441.6u ,708.3u ) .. (416.6u ,733.3u ) .. (391.6u ,708.3u ) .. (416.6u ,683.3u ) .. (441.6u ,708.3u ) .. cycle;
draw pp;
label(btex {\scriptsize 8} etex, (416.6u ,708.3u ));
path pp;
pp = (941.6u ,708.3u ) .. (916.6u ,733.3u ) .. (891.6u ,708.3u ) .. (916.6u ,683.3u ) .. (941.6u ,708.3u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (941.6u ,708.3u ) .. (916.6u ,733.3u ) .. (891.6u ,708.3u ) .. (916.6u ,683.3u ) .. (941.6u ,708.3u ) .. cycle;
draw pp;
label(btex {\scriptsize 4} etex, (916.6u ,708.3u ));
path pp;
pp = (233.3u ,625u ) .. (208.3u ,650u ) .. (183.3u ,625u ) .. (208.3u ,600u ) .. (233.3u ,625u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (233.3u ,625u ) .. (208.3u ,650u ) .. (183.3u ,625u ) .. (208.3u ,600u ) .. (233.3u ,625u ) .. cycle;
draw pp;
label(btex {\scriptsize 3} etex, (208.3u ,625u ));
path pp;
pp = (650u ,625u ) .. (625u ,650u ) .. (600u ,625u ) .. (625u ,600u ) .. (650u ,625u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (650u ,625u ) .. (625u ,650u ) .. (600u ,625u ) .. (625u ,600u ) .. (650u ,625u ) .. cycle;
draw pp;
label(btex {\scriptsize 6} etex, (625u ,625u ));
path pp;
pp = (233.3u ,541.6u ) .. (208.3u ,566.6u ) .. (183.3u ,541.6u ) .. (208.3u ,516.6u ) .. (233.3u ,541.6u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (233.3u ,541.6u ) .. (208.3u ,566.6u ) .. (183.3u ,541.6u ) .. (208.3u ,516.6u ) .. (233.3u ,541.6u ) .. cycle;
draw pp;
label(btex {\scriptsize 7} etex, (208.3u ,541.6u ));
path pp;
pp = (650u ,541.6u ) .. (625u ,566.6u ) .. (600u ,541.6u ) .. (625u ,516.6u ) .. (650u ,541.6u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (650u ,541.6u ) .. (625u ,566.6u ) .. (600u ,541.6u ) .. (625u ,516.6u ) .. (650u ,541.6u ) .. cycle;
draw pp;
label(btex {\scriptsize 2} etex, (625u ,541.6u ));
endfig;

end

