
dont:
	

combine:
	cat \
		C01/*.tex \
		C02/*.tex \
		C03/*.tex \
		C04/*.tex \
		C05/*.tex \
		C06/*.tex \
		C07/*.tex \
		C08/*.tex \
		C09/*.tex \
		C10/*.tex \
		C11/*.tex \
		C12/*.tex \
		C13/*.tex \
		C14/*.tex \
		C15/*.tex \
		C16/*.tex \
		C17/*.tex \
		C18/*.tex \
	>all.tex


html:
	pandoc --toc users_guide.tex -s --mathjax -o users_guide.html
