MY_PATH=../../..
SRC=$(MY_PATH)/src

GROUPS_PATH=$(SRC)/apps/groups


Op42:
	$(GROUPS_PATH)/orthogonal_group.out -v 2 -epsilon 1 -d 4 -q 2

Om42:
	$(GROUPS_PATH)/orthogonal_group.out -v 2 -epsilon -1 -d 4 -q 2

Op62:
	$(GROUPS_PATH)/orthogonal_group.out -v 2 -epsilon 1 -d 6 -q 2

Om62:
	$(GROUPS_PATH)/orthogonal_group.out -v 2 -epsilon -1 -d 6 -q 2

# order 25920, degree 27 = U_4(2) = Weyl group of type E_6 = Sp_4(2) = O_5(3)

