% file: tournament_4_rep_6_2.mp
% created by Orbiter metapost interface
% creation date: Fri Nov 29 20:48:18 MST 2019

input boxes

verbatimtex
\documentclass[10pt]{article}
\usepackage[noBBpl]{mathpazo}
\usepackage{amsmath}
\usepackage{amssymb}
\begin{document}
\scriptsize
etex;
u=0.100000mm;
beginfig(1);
path p[];
pickup pencircle scaled 0.5pt;
drawarrow (850u ,500u )--(587.5u ,762.5u );
drawarrow (850u ,500u )--(325u ,500u );
drawarrow (500u ,150u )--(762.5u ,412.5u );
drawarrow (500u ,850u )--(237.5u ,587.5u );
drawarrow (500u ,850u )--(500u ,325u );
drawarrow (150u ,500u )--(412.5u ,237.5u );
path pp;
pp = (875u ,500u ) .. (850u ,525u ) .. (825u ,500u ) .. (850u ,475u ) .. (875u ,500u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (875u ,500u ) .. (850u ,525u ) .. (825u ,500u ) .. (850u ,475u ) .. (875u ,500u ) .. cycle;
draw pp;
path pp;
pp = (525u ,850u ) .. (500u ,875u ) .. (475u ,850u ) .. (500u ,825u ) .. (525u ,850u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (525u ,850u ) .. (500u ,875u ) .. (475u ,850u ) .. (500u ,825u ) .. (525u ,850u ) .. cycle;
draw pp;
path pp;
pp = (175u ,500u ) .. (150u ,525u ) .. (125u ,500u ) .. (150u ,475u ) .. (175u ,500u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (175u ,500u ) .. (150u ,525u ) .. (125u ,500u ) .. (150u ,475u ) .. (175u ,500u ) .. cycle;
draw pp;
path pp;
pp = (525u ,150u ) .. (500u ,175u ) .. (475u ,150u ) .. (500u ,125u ) .. (525u ,150u ) .. cycle;
fill pp withcolor 1 white;
path pp;
pp = (525u ,150u ) .. (500u ,175u ) .. (475u ,150u ) .. (500u ,125u ) .. (525u ,150u ) .. cycle;
draw pp;
endfig;

end

