MY_PATH=~/DEV.20/GITHUB/orbiter
#MY_PATH=../../..
#MY_PATH=/scratch/betten/COMPILE/orbiter

ORBITER_PATH=$(MY_PATH)/src/apps/orbiter


# Dickson nonsingular:

D1="1,4,1,7,1,12,1,15"
D2= "1,1,1,2,1,3,1,4,1,7,1,11,1,14,1,15,1,19"
D3="1,4,1,7,1,12,1,14,1,15,1,19"
D4="1,3,1,4,1,11,1,9,1,10,1,14,1,17,1,18,1,19"
D5="1,3,1,4,1,8,1,10,1,17,1,18,1,19"
D6="1,2,1,3,1,4,1,7,1,15"
D7="1,2,1,3,1,5,1,9,1,10,1,14,1,15"
D8="1,3,1,4,1,5,1,7,1,10,1,11,1,19"
D9="1,3,1,4,1,7,1,11,1,12,1,15,1,19"
D10="1,4,1,7,1,8,1,9,1,10,1,13,1,15,1,16,1,17"
D11:="1,4,1,7,1,8,1,10,1,13,1,14,1,15,1,16,1,17"
D12="1,4,1,6,1,7,1,8,1,9,1,10,1,15,1,16,1,17"
D13="1,6,1,8,1,9,1,10,1,15,1,16,1,17"
D14="1,6,1,7,1,10,1,11,1,14,1,15"
D15="1,4,1,5,1,6,1,8,1,12,1,14,1,16"
D16=" 1,4,1,7,1,3,1,15,1,12"  
D17="1,4,1,7,1,8,1,9,1,11,1,13,1,15,1,16,1,17,1,18,1,19"
D18="1,4,1,7,1,8,1,11,1,13,1,14,1,15,1,16,1,17,1,18,1,19"
D19= "1,4,1,7,1,6,1,8,1,11,1,14,1,12,1,16,1,17,1,18,1,19 "   
D20="1,4,1,5,1,6,1,7,1,8,1,10,1,13,1,14,1,15"
D21="1,5,1,6,1,8,1,10,1,13,1,14,1,15"
D22="1,4,1,5,1,7,1,9,1,10,1,11,1,13,1,14,1,15,1,18,1,19"
D23="1,4,1,7,1,9,1,11,1,13,1,14,1,15,1,18,1,19"
D24="1,5,1,8,1,9,1,10,1,13,1,14,1,15,1,18,1,19"
D25= "1,5,1,10,1,13,1,11,1,9,1,14,1,15,1,18,1,19 "   
D26="1,5,1,6,1,8,1,10,1,15,1,18,1,19"
D27="1,4,1,5,1,7,1,10,1,11,1,12,1,13,1,14,1,17,1,18"
D28="1,4,1,5,1,6,1,7,1,10,1,11,1,14,1,15,1,17,1,18"
D29="1,4,1,7,1,13,1,11,1,9,1,15,1,17,1,18"
D30= "1,0,1,1,1,2,1,3,1,7,1,10,1,11,1,16"   
D31="1,0,1,1,1,2,1,5,1,7,1,11,1,13,1,14,1,15,1,17,1,18,1,19"
D32="1,0,1,1,1,2,1,3,1,7,1,8,1,10,1,11,1,12,1,15,1,16,1,19"
D33="1,0,1,1,1,2,1,3,1,6,1,7,1,10,1,12,1,13,1,15,1,16,1,19"
D34= "1,0,1,1,1,2,1,3,1,7,1,10,1,16,1,19"  
D35="1,0,1,1,1,2,1,3,1,6,1,7,1,8,1,11,1,13,1,15"
D36="1,0,1,1,1,2,1,3,1,7,1,15"
D37="1,0,1,1,1,2,1,3,1,7,1,12,1,15,1,19"
D38="1,0,1,1,1,2,1,3,1,6,1,7,1,12,1,13,1,15,1,19"
D39= "1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,12,1,15,1,19"  
D40= "1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,6,1,13,1,19 "   
D41="1,2,1,4,1,7,1,5,1,10,1,11,1,14,1,19"
D42="1,2,1,4,1,7,1,11,1,12,1,14,1,15,1,19"
D43= "1,0,1,1,1,2,1,7,1,13,1,8,1,11,1,14,1,15,1,17 "   
D44="1,0,1,1,1,2,1,6,1,8,1,11,1,12,1,14"
D45="1,6,1,8,1,9,1,11,1,12,1,13,1,14,1,15,1,16,1,17,1,18,1,19"
D46="1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,12,1,15,1,16,1,17,1,18,1,19" 
D47="1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,16,1,17,1,18,1,19 "

ND1="1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,12,1,15,1,19"
ND2="1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,6,1,13,1,19 " 
ND3="1,0,1,1,1,2,1,3,1,7,1,19 " 
ND4="1,0,1,1,1,2,1,7,1,13,1,8,1,11,1,14,1,15,1,17 " 
ND5="1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,12,1,15,1,16,1,17,1,18,1,19" 
ND6="1,5,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,16,1,17,1,18,1,19 " 
ND7="1,0,1,1,1,2,1,3,1,7,1,10,1,11,1,16" 
ND8="1,5,1,10,1,13,1,11,1,9,1,14,1,15,1,18,1,19 " 
ND9="1,5,1,10,1,6,1,8,1,15,1,18,1,19 " 
ND10="1,4,1,7,1,6,1,8,1,11,1,14,1,12,1,16,1,17,1,18,1,19 "         

T1="1,0,1,1,1,2,1,3,1,7,1,6,1,13,1,8,1,11,1,12,1,15,1,19"
T2=" 1,0,1,1,1,2,1,3,1,7,1,6,1,13,1,8,1,11,1,19 " 
T3="1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,9,1,14,1,12,1,15,1,19" 
T4=" 1,0,1,1,1,2,1,3,1,7,1,5,1,10,1,9,1,14,1,19 " 
T5="1,0,1,1,1,2,1,3,1,7,1,9,1,14,1,12,1,15,1,19"    
T6=" 1,0,1,1,1,2,1,3,1,7,1,9,1,14,1,19 " 
T7="1,4,1,7,1,3,1,15,1,12"  

A1="1,0,1,1,1,2,1,3,1,7,1,10,1,6,1,13,1,8,1,11,1,9,1,14,1,12,1,15,1,16,1,19"
A2="1,0,1,1,1,2,1,3,1,7,1,10,1,6,1,13,1,8,1,11,1,12,1,15,1,16,1,19"  
A3="1,0,1,1,1,2,1,3,1,7,1,10,1,6,1,13,1,8,1,11,1,16,1,19"
A4="1,0,1,1,1,2,1,3,1,7,1,10,1,8,1,11,1,9,1,14,1,12,1,15,1,16,1,19"  
A5="1,0,1,1,1,2,1,3,1,7,1,10,1,8,1,11,1,16,1,19"
A6="1,0,1,1,1,2,1,3,1,7,1,10,1,6,1,13,1,9,1,14,1,12,1,15,1,16,1,19"  
A7="1,0,1,1,1,2,1,3,1,7,1,10,1,6,1,13,1,16,1,19"
A8="1,0,1,1,1,2,1,3,1,7,1,10,1,9,1,14,1,12,1,15,1,16,1,19"  
A9="1,0,1,1,1,2,1,3,1,7,1,10,1,12,1,15,1,16,1,19"
A10="1,0,1,1,1,2,1,3,1,7,1,10,1,16,1,19"  

PGL_4_2:
	$(ORBITER_PATH)/orbiter.out -v 2 -linear_group -PGL 4 2 -end \
		-group_theoretic_activities \
		-report \
		-draw_options -rad 200 -end \
		-end
	pdflatex PGL_4_2_report.tex
	open PGL_4_2_report.pdf




PG_3_2_subsets:
	$(ORBITER_PATH)/orbiter.out -v 4 -define G -linear_group -PGL 4 2 -end -end \
		-with G -do \
		-group_theoretic_activities \
			-poset_classification_control -problem_label PGL_4_2 -depth 15 -draw_poset \
				-draw_options -rad 200 -embedded -end \
			-end \
			-orbits_on_subsets 15 \
			-draw_poset \
			-draw_options -end \
			-report \
		-end
	pdflatex PGL_4_2_poset_lvl_15.tex
	open PGL_4_2_poset_lvl_15.pdf
	#pdflatex PGL_4_2_poset_detailed_lvl_15.tex
	#open PGL_4_2_poset_detailed_lvl_15.pdf


orbits_cubic_surfaces_q2:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-define G -linear_group -PGL 4 2 -end -end \
		-with G -do \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-orbits_on_polynomials_draw_tree 6 \
		-draw_options -yout 500000 -rad 15 -nodes_empty -line_width 0.5 -y_stretch 0.25 -embedded -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf



properties_q2:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2.csv 2 \
		-end 


# 3 points:
Dickson4m1="1,3,1,4,1,11,1,9,1,10,1,14,1,17,1,18,1,19"
Dickson4m1_bit="0,0,0,1,1,0,0,0,0,1,1,1,0,0,1,0,0,1,1,1"
Dickson4m1_rank=937496

Dickson4m0="1,3,1,4,1,11,1,10,1,17,1,18,1,19"
Dickson4m0_bit="0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1"
Dickson4m0_rank=920600



Dickson6="1,3,1,4,1,8,1,10,1,17,1,18,1,19"
Dickson6_bit="0,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,1,1,1"
Dickson6_rank=918808


Dickson7="1,2,1,3,1,15,1,4,1,7"
Dickson7_bit="0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0"
Dickson7_rank=32928


Dickson7b="1,2,1,3,1,15"
Dickson7b_bit="0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0"
Dickson7b_rank=32784

Dickson8="1,2,1,3,1,5,1,9,1,10,1,14,1,15"
Dickson8_bit="0,0,1,1,0,1,0,0,0,1,1,0,0,0,1,1,0,0,0,0"
Dickson8_rank=50736

Dickson7c="1,2,1,3,1,5,1,10,1,15"
Dickson7c_bit="0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0"
Dickson7c_rank=33840



orbits_cubic_surfaces_q2_recognize:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-recognize_orbits_on_polynomials "$(Dickson4m1_rank), $(Dickson4m0_rank), $(Dickson6_rank), $(Dickson7_rank), $(Dickson7b_rank), $(Dickson8_rank), $(Dickson7c_rank)" 
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf


#recognizing object 0 / 7 which is 937496
#recognizing object 0 / 7, point 937496 lies in orbit 80
#recognizing object 1 / 7 which is 920600
#recognizing object 1 / 7, point 920600 lies in orbit 70
#recognizing object 2 / 7 which is 918808
#recognizing object 2 / 7, point 918808 lies in orbit 84
#recognizing object 3 / 7 which is 32928
#recognizing object 3 / 7, point 32928 lies in orbit 17
#recognizing object 4 / 7 which is 32784
#recognizing object 4 / 7, point 32784 lies in orbit 7
#recognizing object 5 / 7 which is 50736
#recognizing object 5 / 7, point 50736 lies in orbit 21
#recognizing object 6 / 7 which is 33840
#recognizing object 6 / 7, point 33840 lies in orbit 13



Dickson4m1_q2:
	$(ORBITER_PATH)/orbiter.out -v 3 -linear_group -PGL 4 2 -wedge -end \
		-group_theoretic_activities \
		-control_six_arcs -end \
		-create_surface -by_coefficients $(Dickson4m1) -q 2 \
		-end \
		-end 
	pdflatex surface_by_coefficients_q2_report.tex
	open surface_by_coefficients_q2_report.pdf
	mv surface_by_coefficients_q2_points.txt surface_by_coefficients_q2_D6_points.txt

Dickson4m0_q2:
	$(ORBITER_PATH)/orbiter.out -v 3 -linear_group -PGL 4 2 -wedge -end \
		-group_theoretic_activities \
		-control_six_arcs -end \
		-create_surface -by_coefficients $(Dickson4m0) -q 2 \
		-end \
		-end 
	pdflatex surface_by_coefficients_q2_report.tex
	open surface_by_coefficients_q2_report.pdf
	mv surface_by_coefficients_q2_points.txt surface_by_coefficients_q2_D6_points.txt


Dickson7b_q2:
	$(ORBITER_PATH)/orbiter.out -v 3 -linear_group -PGL 4 2 -wedge -end \
		-group_theoretic_activities \
		-control_six_arcs -end \
		-create_surface -by_coefficients $(Dickson7b) -q 2 \
		-end \
		-end 
	pdflatex surface_by_coefficients_q2_report.tex
	open surface_by_coefficients_q2_report.pdf

Dickson7c_q2:
	$(ORBITER_PATH)/orbiter.out -v 3 -linear_group -PGL 4 2 -wedge -end \
		-group_theoretic_activities \
		-control_six_arcs -end \
		-create_surface -by_coefficients $(Dickson7c) -q 2 \
		-end \
		-end 
	pdflatex surface_by_coefficients_q2_report.tex
	open surface_by_coefficients_q2_report.pdf


rank:
	$(ORBITER_PATH)/orbiter.out -v 4 -finite_field_activity -q 2 -rank_point_in_PG 19 \
		$(Dickson7c_bit) \
		-end


NR1=589807
NR2=533743
NR3=524431
NR4=190857
NR5=1048416
NR6=1011552
NR7=68754
NR8=847392
NR9=820576
NR10=1006032

TR1=571855
TR2=534991
TR3=579247
TR4=542383
TR5=578191
TR6=541327
TR7=37020

AR1=655311
AR2=638415
AR3=601551
AR4=647055
AR5=593295
AR6=653007
AR7=599247
AR8=644751
AR9=627855
AR10=590991


R1=37012
R2=575646
R3=577680
R4=937496
R5=918808
R6=32928
R7=50736
R8=527544
R9=563352
R10=239506
R11=255378
R12=231378
R13=231234
R14=52420
R15=86387
R16=37020
R17=1026960
R18=1042832
R19=1006032
R20=58868
R21=58724
R22=847536
R23=846480
R24=845600
R25=847392
R26=820576
R27=425137
R28=445681
R29=436881
R30=68754
R31=977063
R32=630159
R33=636111
R34=590991
R35=43475
R36=32915
R37=561295
R38=569551
R39=589807
R40=533743
R41=543924
R42=579732
R43=190857
R44=22860
R45=1047360
R46=1048416
R47=1011552




rank_all:
	$(ORBITER_PATH)/orbiter.out -v 4 -finite_field_activity -q 2 -rank_point_in_PG_given_as_pairs 19 $(D18) \
		-end



orbits_cubic_surfaces_q2_with_recognition:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-recognize_orbits_on_polynomials "$(R1), $(R2), $(R3), $(R4), $(R5), $(R6), $(R7), $(R8), $(R9), $(R10), $(R11), $(R12), $(R13), $(R14), $(R15), $(R16), $(R17), $(R18), $(R19), $(R20), $(R21), $(R22), $(R23), $(R24), $(R25), $(R26), $(R27), $(R28), $(R29), $(R30), $(R31), $(R32), $(R33), $(R34), $(R35), $(R36), $(R37), $(R38), $(R39), $(R40), $(R41), $(R42), $(R43), $(R44), $(R45), $(R46), $(R47)" \
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf


# write poly_orbits_d3_n3_q2_recognition.csv
# the orbiter numbers of the Dickson surfaces are:
#28,113,130,80,84,17,21,110,101,91,50,52,59,26,117,6,38,39,61,11,15,122,121,138,96,134,76,73,75,65,112,136,118,140,27,24,57,49,87,92,131,102,79,20,137,135,129


select:
	$(ORBITER_PATH)/orbiter.out -v 4 -csv_file_select_rows poly_orbits_d3_n3_q2.csv \
		"28,113,130,80,84,17,21,110,101,91,50,52,59,26,117,6,38,39,61,11,15,122,121,138,96,134,76,73,75,65,112,136,118,140,27,24,57,49,87,92,131,102,79,20,137,135,129"

# writes poly_orbits_d3_n3_q2_select.csv


#blah:
#recognizing object 0 / 47, point 37012 lies in orbit 28
#recognizing object 1 / 47, point 575646 lies in orbit 113
#recognizing object 2 / 47, point 577680 lies in orbit 130
#recognizing object 3 / 47, point 937496 lies in orbit 80
#recognizing object 4 / 47, point 918808 lies in orbit 84
#recognizing object 5 / 47, point 32928 lies in orbit 17
#recognizing object 6 / 47, point 50736 lies in orbit 21
#recognizing object 7 / 47, point 527544 lies in orbit 110
#recognizing object 8 / 47, point 563352 lies in orbit 101
#recognizing object 9 / 47, point 239506 lies in orbit 91
#recognizing object 10 / 47, point 255378 lies in orbit 50
#recognizing object 11 / 47, point 231378 lies in orbit 52
#recognizing object 12 / 47, point 231234 lies in orbit 59
#recognizing object 13 / 47, point 52420 lies in orbit 26
#recognizing object 14 / 47, point 86387 lies in orbit 117
#recognizing object 15 / 47, point 37020 lies in orbit 6
#recognizing object 16 / 47, point 1026960 lies in orbit 38
#recognizing object 17 / 47, point 1042832 lies in orbit 39
#recognizing object 18 / 47, point 1006032 lies in orbit 61
#recognizing object 19 / 47, point 58868 lies in orbit 11
#recognizing object 20 / 47, point 58724 lies in orbit 15
#recognizing object 21 / 47, point 847536 lies in orbit 122
#recognizing object 22 / 47, point 846480 lies in orbit 121
#recognizing object 23 / 47, point 845600 lies in orbit 138
#recognizing object 24 / 47, point 847392 lies in orbit 96
#recognizing object 25 / 47, point 820576 lies in orbit 134
#recognizing object 26 / 47, point 425137 lies in orbit 76
#recognizing object 27 / 47, point 445681 lies in orbit 73
#recognizing object 28 / 47, point 436881 lies in orbit 75
#recognizing object 29 / 47, point 68754 lies in orbit 65
#recognizing object 30 / 47, point 977063 lies in orbit 112
#recognizing object 31 / 47, point 630159 lies in orbit 136
#recognizing object 32 / 47, point 636111 lies in orbit 118
#recognizing object 33 / 47, point 590991 lies in orbit 140
#recognizing object 34 / 47, point 43475 lies in orbit 27
#recognizing object 35 / 47, point 32915 lies in orbit 24
#recognizing object 36 / 47, point 561295 lies in orbit 57
#recognizing object 37 / 47, point 569551 lies in orbit 49
#recognizing object 38 / 47, point 589807 lies in orbit 87
#recognizing object 39 / 47, point 533743 lies in orbit 92
#recognizing object 40 / 47, point 543924 lies in orbit 131
#recognizing object 41 / 47, point 579732 lies in orbit 102
#recognizing object 42 / 47, point 190857 lies in orbit 79
#recognizing object 43 / 47, point 22860 lies in orbit 20
#recognizing object 44 / 47, point 1047360 lies in orbit 137
#recognizing object 45 / 47, point 1048416 lies in orbit 135
#recognizing object 46 / 47, point 1011552 lies in orbit 129

orbits_cubic_surfaces_q2_with_recognition_NR:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-recognize_orbits_on_polynomials "$(NR1), $(NR2), $(NR3), $(NR4), $(NR5), $(NR6), $(NR7), $(NR8), $(NR9), $(NR10) " \
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf

#recognition:
#recognizing object 0 / 10, point 589807 lies in orbit 87
#recognizing object 1 / 10, point 533743 lies in orbit 92
#recognizing object 2 / 10, point 524431 lies in orbit 48
#recognizing object 3 / 10, point 190857 lies in orbit 79
#recognizing object 4 / 10, point 1048416 lies in orbit 135
#recognizing object 5 / 10, point 1011552 lies in orbit 129
#recognizing object 6 / 10, point 68754 lies in orbit 65
#recognizing object 7 / 10, point 847392 lies in orbit 96
#recognizing object 8 / 10, point 820576 lies in orbit 134
#recognizing object 9 / 10, point 1006032 lies in orbit 61


orbits_cubic_surfaces_q2_with_recognition_T:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-recognize_orbits_on_polynomials "$(TR1), $(TR2), $(TR3), $(TR4), $(TR5), $(TR6), $(TR7)" \
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf


orbits_cubic_surfaces_q2_with_recognition_A:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-orbits_on_polynomials 3 \
		-recognize_orbits_on_polynomials "$(AR1), $(AR2), $(AR3), $(AR4), $(AR5), $(AR6), $(AR7), $(AR8), $(AR9), $(AR10)" \
		-end 
	pdflatex poly_orbits_d3_n3_q2.tex
	open poly_orbits_d3_n3_q2.pdf


# investigate orbiter number 11, 15 over extension fields



Surfaces_q2:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q4:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 4 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q8:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 8 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q16:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 16 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q32:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 32 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q64:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 64 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties poly_orbits_d3_n3_q2_select.csv 2 1 \
		-end 

Surfaces_q2_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGL 4 2 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F2.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F2_report.tex
	open poly_orbits_d3_n3_q2_select_F2_report.pdf

Surfaces_q4_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 4 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F4.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F4_report.tex
	open poly_orbits_d3_n3_q2_select_F4_report.pdf

Surfaces_q8_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 8 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F8.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F8_report.tex
	open poly_orbits_d3_n3_q2_select_F8_report.pdf

Surfaces_q16_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 16 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F16.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F16_report.tex
	open poly_orbits_d3_n3_q2_select_F16_report.pdf

Surfaces_q32_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 32 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F32.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F32_report.tex
	open poly_orbits_d3_n3_q2_select_F32_report.pdf

Surfaces_q64_analyze:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-linear_group -PGGL 4 64 \
		-end \
		-group_theoretic_activities \
		-cubic_surface_properties_analyze poly_orbits_d3_n3_q2_select_F64.csv 2 \
		-draw_options -end \
		-end 
	pdflatex poly_orbits_d3_n3_q2_select_F64_report.tex
	open poly_orbits_d3_n3_q2_select_F64_report.pdf


join:
	$(ORBITER_PATH)/orbiter.out -v 4 \
		-csv_file_join poly_orbits_d3_n3_q2_select_F2.csv Orbit_idx \
		-csv_file_join poly_orbits_d3_n3_q2_select_F4.csv Orbit_idx \
		-csv_file_join poly_orbits_d3_n3_q2_select_F8.csv Orbit_idx \
		-csv_file_join poly_orbits_d3_n3_q2_select_F16.csv Orbit_idx \
		-csv_file_join poly_orbits_d3_n3_q2_select_F32.csv Orbit_idx 
	